// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/assign_op.proto

#ifndef PROTOBUF_proto_2fassign_5fop_2eproto__INCLUDED
#define PROTOBUF_proto_2fassign_5fop_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace ps {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fassign_5fop_2eproto();
void protobuf_AssignDesc_proto_2fassign_5fop_2eproto();
void protobuf_ShutdownFile_proto_2fassign_5fop_2eproto();


enum AsOp {
  ASSIGN = 0,
  PLUS = 1,
  MINUS = 2,
  TIMES = 3,
  DIVIDE = 4,
  AND = 5,
  OR = 6,
  XOR = 7
};
bool AsOp_IsValid(int value);
const AsOp AsOp_MIN = ASSIGN;
const AsOp AsOp_MAX = XOR;
const int AsOp_ARRAYSIZE = AsOp_MAX + 1;

const ::google::protobuf::EnumDescriptor* AsOp_descriptor();
inline const ::std::string& AsOp_Name(AsOp value) {
  return ::google::protobuf::internal::NameOfEnum(
    AsOp_descriptor(), value);
}
inline bool AsOp_Parse(
    const ::std::string& name, AsOp* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AsOp>(
    AsOp_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace ps

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ps::AsOp>() {
  return ::ps::AsOp_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fassign_5fop_2eproto__INCLUDED
