// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/filter.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto/filter.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ps {

namespace {

const ::google::protobuf::Descriptor* Filter_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Filter_reflection_ = NULL;
const ::google::protobuf::Descriptor* Filter_FixedFloatConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Filter_FixedFloatConfig_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Filter_Type_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_2ffilter_2eproto() {
  protobuf_AddDesc_proto_2ffilter_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto/filter.proto");
  GOOGLE_CHECK(file != NULL);
  Filter_descriptor_ = file->message_type(0);
  static const int Filter_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, clear_cache_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, num_bytes_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, mean_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, std_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, fixed_point_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, signature_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, uncompressed_size_),
  };
  Filter_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Filter_descriptor_,
      Filter::default_instance_,
      Filter_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Filter));
  Filter_FixedFloatConfig_descriptor_ = Filter_descriptor_->nested_type(0);
  static const int Filter_FixedFloatConfig_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter_FixedFloatConfig, min_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter_FixedFloatConfig, max_value_),
  };
  Filter_FixedFloatConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Filter_FixedFloatConfig_descriptor_,
      Filter_FixedFloatConfig::default_instance_,
      Filter_FixedFloatConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter_FixedFloatConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Filter_FixedFloatConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Filter_FixedFloatConfig));
  Filter_Type_descriptor_ = Filter_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_2ffilter_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Filter_descriptor_, &Filter::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Filter_FixedFloatConfig_descriptor_, &Filter_FixedFloatConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_2ffilter_2eproto() {
  delete Filter::default_instance_;
  delete Filter_reflection_;
  delete Filter_FixedFloatConfig::default_instance_;
  delete Filter_FixedFloatConfig_reflection_;
}

void protobuf_AddDesc_proto_2ffilter_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022proto/filter.proto\022\002ps\"\377\002\n\006Filter\022\035\n\004t"
    "ype\030\001 \002(\0162\017.ps.Filter.Type\022\032\n\013clear_cach"
    "e\030\024 \001(\010:\005false\022\024\n\tnum_bytes\030\005 \001(\005:\0013\022\014\n\004"
    "mean\030\006 \001(\002\022\013\n\003std\030\007 \001(\002\0220\n\013fixed_point\030\004"
    " \003(\0132\033.ps.Filter.FixedFloatConfig\022\021\n\tsig"
    "nature\030\002 \001(\004\022\031\n\021uncompressed_size\030\003 \003(\004\032"
    "\?\n\020FixedFloatConfig\022\025\n\tmin_value\030\001 \001(\002:\002"
    "-1\022\024\n\tmax_value\030\002 \001(\002:\0011\"h\n\004Type\022\017\n\013KEY_"
    "CACHING\020\001\022\017\n\013COMPRESSING\020\002\022\020\n\014FIXING_FLO"
    "AT\020\003\022\t\n\005NOISE\020\004\022\r\n\tDELTA_KEY\020\005\022\022\n\016TRUNCA"
    "TE_FLOAT\020\006", 410);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/filter.proto", &protobuf_RegisterTypes);
  Filter::default_instance_ = new Filter();
  Filter_FixedFloatConfig::default_instance_ = new Filter_FixedFloatConfig();
  Filter::default_instance_->InitAsDefaultInstance();
  Filter_FixedFloatConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_2ffilter_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_2ffilter_2eproto {
  StaticDescriptorInitializer_proto_2ffilter_2eproto() {
    protobuf_AddDesc_proto_2ffilter_2eproto();
  }
} static_descriptor_initializer_proto_2ffilter_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* Filter_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Filter_Type_descriptor_;
}
bool Filter_Type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Filter_Type Filter::KEY_CACHING;
const Filter_Type Filter::COMPRESSING;
const Filter_Type Filter::FIXING_FLOAT;
const Filter_Type Filter::NOISE;
const Filter_Type Filter::DELTA_KEY;
const Filter_Type Filter::TRUNCATE_FLOAT;
const Filter_Type Filter::Type_MIN;
const Filter_Type Filter::Type_MAX;
const int Filter::Type_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int Filter_FixedFloatConfig::kMinValueFieldNumber;
const int Filter_FixedFloatConfig::kMaxValueFieldNumber;
#endif  // !_MSC_VER

Filter_FixedFloatConfig::Filter_FixedFloatConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Filter_FixedFloatConfig::InitAsDefaultInstance() {
}

Filter_FixedFloatConfig::Filter_FixedFloatConfig(const Filter_FixedFloatConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Filter_FixedFloatConfig::SharedCtor() {
  _cached_size_ = 0;
  min_value_ = -1;
  max_value_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Filter_FixedFloatConfig::~Filter_FixedFloatConfig() {
  SharedDtor();
}

void Filter_FixedFloatConfig::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Filter_FixedFloatConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Filter_FixedFloatConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Filter_FixedFloatConfig_descriptor_;
}

const Filter_FixedFloatConfig& Filter_FixedFloatConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2ffilter_2eproto();
  return *default_instance_;
}

Filter_FixedFloatConfig* Filter_FixedFloatConfig::default_instance_ = NULL;

Filter_FixedFloatConfig* Filter_FixedFloatConfig::New() const {
  return new Filter_FixedFloatConfig;
}

void Filter_FixedFloatConfig::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    min_value_ = -1;
    max_value_ = 1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Filter_FixedFloatConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float min_value = 1 [default = -1];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &min_value_)));
          set_has_min_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_max_value;
        break;
      }

      // optional float max_value = 2 [default = 1];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_max_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &max_value_)));
          set_has_max_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Filter_FixedFloatConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional float min_value = 1 [default = -1];
  if (has_min_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->min_value(), output);
  }

  // optional float max_value = 2 [default = 1];
  if (has_max_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->max_value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Filter_FixedFloatConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional float min_value = 1 [default = -1];
  if (has_min_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->min_value(), target);
  }

  // optional float max_value = 2 [default = 1];
  if (has_max_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->max_value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Filter_FixedFloatConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional float min_value = 1 [default = -1];
    if (has_min_value()) {
      total_size += 1 + 4;
    }

    // optional float max_value = 2 [default = 1];
    if (has_max_value()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Filter_FixedFloatConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Filter_FixedFloatConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Filter_FixedFloatConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Filter_FixedFloatConfig::MergeFrom(const Filter_FixedFloatConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_min_value()) {
      set_min_value(from.min_value());
    }
    if (from.has_max_value()) {
      set_max_value(from.max_value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Filter_FixedFloatConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Filter_FixedFloatConfig::CopyFrom(const Filter_FixedFloatConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Filter_FixedFloatConfig::IsInitialized() const {

  return true;
}

void Filter_FixedFloatConfig::Swap(Filter_FixedFloatConfig* other) {
  if (other != this) {
    std::swap(min_value_, other->min_value_);
    std::swap(max_value_, other->max_value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Filter_FixedFloatConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Filter_FixedFloatConfig_descriptor_;
  metadata.reflection = Filter_FixedFloatConfig_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Filter::kTypeFieldNumber;
const int Filter::kClearCacheFieldNumber;
const int Filter::kNumBytesFieldNumber;
const int Filter::kMeanFieldNumber;
const int Filter::kStdFieldNumber;
const int Filter::kFixedPointFieldNumber;
const int Filter::kSignatureFieldNumber;
const int Filter::kUncompressedSizeFieldNumber;
#endif  // !_MSC_VER

Filter::Filter()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Filter::InitAsDefaultInstance() {
}

Filter::Filter(const Filter& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Filter::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  clear_cache_ = false;
  num_bytes_ = 3;
  mean_ = 0;
  std_ = 0;
  signature_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Filter::~Filter() {
  SharedDtor();
}

void Filter::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Filter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Filter::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Filter_descriptor_;
}

const Filter& Filter::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2ffilter_2eproto();
  return *default_instance_;
}

Filter* Filter::default_instance_ = NULL;

Filter* Filter::New() const {
  return new Filter;
}

void Filter::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    clear_cache_ = false;
    num_bytes_ = 3;
    mean_ = 0;
    std_ = 0;
    signature_ = GOOGLE_ULONGLONG(0);
  }
  fixed_point_.Clear();
  uncompressed_size_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Filter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .ps.Filter.Type type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ps::Filter_Type_IsValid(value)) {
            set_type(static_cast< ::ps::Filter_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_signature;
        break;
      }

      // optional uint64 signature = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_signature:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &signature_)));
          set_has_signature();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_uncompressed_size;
        break;
      }

      // repeated uint64 uncompressed_size = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_uncompressed_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 24, input, this->mutable_uncompressed_size())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_uncompressed_size())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_uncompressed_size;
        if (input->ExpectTag(34)) goto parse_fixed_point;
        break;
      }

      // repeated .ps.Filter.FixedFloatConfig fixed_point = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_fixed_point:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_fixed_point()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_fixed_point;
        if (input->ExpectTag(40)) goto parse_num_bytes;
        break;
      }

      // optional int32 num_bytes = 5 [default = 3];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_num_bytes:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_bytes_)));
          set_has_num_bytes();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(53)) goto parse_mean;
        break;
      }

      // optional float mean = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_mean:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &mean_)));
          set_has_mean();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(61)) goto parse_std;
        break;
      }

      // optional float std = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_std:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &std_)));
          set_has_std();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(160)) goto parse_clear_cache;
        break;
      }

      // optional bool clear_cache = 20 [default = false];
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_clear_cache:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &clear_cache_)));
          set_has_clear_cache();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Filter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .ps.Filter.Type type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional uint64 signature = 2;
  if (has_signature()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->signature(), output);
  }

  // repeated uint64 uncompressed_size = 3;
  for (int i = 0; i < this->uncompressed_size_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      3, this->uncompressed_size(i), output);
  }

  // repeated .ps.Filter.FixedFloatConfig fixed_point = 4;
  for (int i = 0; i < this->fixed_point_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->fixed_point(i), output);
  }

  // optional int32 num_bytes = 5 [default = 3];
  if (has_num_bytes()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->num_bytes(), output);
  }

  // optional float mean = 6;
  if (has_mean()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->mean(), output);
  }

  // optional float std = 7;
  if (has_std()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->std(), output);
  }

  // optional bool clear_cache = 20 [default = false];
  if (has_clear_cache()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(20, this->clear_cache(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Filter::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .ps.Filter.Type type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional uint64 signature = 2;
  if (has_signature()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->signature(), target);
  }

  // repeated uint64 uncompressed_size = 3;
  for (int i = 0; i < this->uncompressed_size_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(3, this->uncompressed_size(i), target);
  }

  // repeated .ps.Filter.FixedFloatConfig fixed_point = 4;
  for (int i = 0; i < this->fixed_point_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->fixed_point(i), target);
  }

  // optional int32 num_bytes = 5 [default = 3];
  if (has_num_bytes()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->num_bytes(), target);
  }

  // optional float mean = 6;
  if (has_mean()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->mean(), target);
  }

  // optional float std = 7;
  if (has_std()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->std(), target);
  }

  // optional bool clear_cache = 20 [default = false];
  if (has_clear_cache()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(20, this->clear_cache(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Filter::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .ps.Filter.Type type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional bool clear_cache = 20 [default = false];
    if (has_clear_cache()) {
      total_size += 2 + 1;
    }

    // optional int32 num_bytes = 5 [default = 3];
    if (has_num_bytes()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->num_bytes());
    }

    // optional float mean = 6;
    if (has_mean()) {
      total_size += 1 + 4;
    }

    // optional float std = 7;
    if (has_std()) {
      total_size += 1 + 4;
    }

    // optional uint64 signature = 2;
    if (has_signature()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->signature());
    }

  }
  // repeated .ps.Filter.FixedFloatConfig fixed_point = 4;
  total_size += 1 * this->fixed_point_size();
  for (int i = 0; i < this->fixed_point_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->fixed_point(i));
  }

  // repeated uint64 uncompressed_size = 3;
  {
    int data_size = 0;
    for (int i = 0; i < this->uncompressed_size_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->uncompressed_size(i));
    }
    total_size += 1 * this->uncompressed_size_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Filter::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Filter* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Filter*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Filter::MergeFrom(const Filter& from) {
  GOOGLE_CHECK_NE(&from, this);
  fixed_point_.MergeFrom(from.fixed_point_);
  uncompressed_size_.MergeFrom(from.uncompressed_size_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_clear_cache()) {
      set_clear_cache(from.clear_cache());
    }
    if (from.has_num_bytes()) {
      set_num_bytes(from.num_bytes());
    }
    if (from.has_mean()) {
      set_mean(from.mean());
    }
    if (from.has_std()) {
      set_std(from.std());
    }
    if (from.has_signature()) {
      set_signature(from.signature());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Filter::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Filter::CopyFrom(const Filter& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Filter::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Filter::Swap(Filter* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(clear_cache_, other->clear_cache_);
    std::swap(num_bytes_, other->num_bytes_);
    std::swap(mean_, other->mean_);
    std::swap(std_, other->std_);
    fixed_point_.Swap(&other->fixed_point_);
    std::swap(signature_, other->signature_);
    uncompressed_size_.Swap(&other->uncompressed_size_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Filter::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Filter_descriptor_;
  metadata.reflection = Filter_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ps

// @@protoc_insertion_point(global_scope)
