// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/param.proto

#ifndef PROTOBUF_proto_2fparam_2eproto__INCLUDED
#define PROTOBUF_proto_2fparam_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ps {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fparam_2eproto();
void protobuf_AssignDesc_proto_2fparam_2eproto();
void protobuf_ShutdownFile_proto_2fparam_2eproto();

class ParamCall;
class ParamInitConfig;
class Timestamp;
class TailKeyIFilter;

enum ParamInitConfig_Type {
  ParamInitConfig_Type_ZERO = 1,
  ParamInitConfig_Type_CONSTANT = 2,
  ParamInitConfig_Type_GAUSSIAN = 3,
  ParamInitConfig_Type_FILE = 4,
  ParamInitConfig_Type_CLONE = 5
};
bool ParamInitConfig_Type_IsValid(int value);
const ParamInitConfig_Type ParamInitConfig_Type_Type_MIN = ParamInitConfig_Type_ZERO;
const ParamInitConfig_Type ParamInitConfig_Type_Type_MAX = ParamInitConfig_Type_CLONE;
const int ParamInitConfig_Type_Type_ARRAYSIZE = ParamInitConfig_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* ParamInitConfig_Type_descriptor();
inline const ::std::string& ParamInitConfig_Type_Name(ParamInitConfig_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    ParamInitConfig_Type_descriptor(), value);
}
inline bool ParamInitConfig_Type_Parse(
    const ::std::string& name, ParamInitConfig_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ParamInitConfig_Type>(
    ParamInitConfig_Type_descriptor(), name, value);
}
// ===================================================================

class ParamCall : public ::google::protobuf::Message {
 public:
  ParamCall();
  virtual ~ParamCall();

  ParamCall(const ParamCall& from);

  inline ParamCall& operator=(const ParamCall& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ParamCall& default_instance();

  void Swap(ParamCall* other);

  // implements Message ----------------------------------------------

  ParamCall* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ParamCall& from);
  void MergeFrom(const ParamCall& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool push = 1 [default = true];
  inline bool has_push() const;
  inline void clear_push();
  static const int kPushFieldNumber = 1;
  inline bool push() const;
  inline void set_push(bool value);

  // optional bool dyn_val_size = 4 [default = false];
  inline bool has_dyn_val_size() const;
  inline void clear_dyn_val_size();
  static const int kDynValSizeFieldNumber = 4;
  inline bool dyn_val_size() const;
  inline void set_dyn_val_size(bool value);

  // optional .ps.TailKeyIFilter tail_filter = 3;
  inline bool has_tail_filter() const;
  inline void clear_tail_filter();
  static const int kTailFilterFieldNumber = 3;
  inline const ::ps::TailKeyIFilter& tail_filter() const;
  inline ::ps::TailKeyIFilter* mutable_tail_filter();
  inline ::ps::TailKeyIFilter* release_tail_filter();
  inline void set_allocated_tail_filter(::ps::TailKeyIFilter* tail_filter);

  // optional bool replica = 10;
  inline bool has_replica() const;
  inline void clear_replica();
  static const int kReplicaFieldNumber = 10;
  inline bool replica() const;
  inline void set_replica(bool value);

  // repeated .ps.Timestamp backup = 11;
  inline int backup_size() const;
  inline void clear_backup();
  static const int kBackupFieldNumber = 11;
  inline const ::ps::Timestamp& backup(int index) const;
  inline ::ps::Timestamp* mutable_backup(int index);
  inline ::ps::Timestamp* add_backup();
  inline const ::google::protobuf::RepeatedPtrField< ::ps::Timestamp >&
      backup() const;
  inline ::google::protobuf::RepeatedPtrField< ::ps::Timestamp >*
      mutable_backup();

  // @@protoc_insertion_point(class_scope:ps.ParamCall)
 private:
  inline void set_has_push();
  inline void clear_has_push();
  inline void set_has_dyn_val_size();
  inline void clear_has_dyn_val_size();
  inline void set_has_tail_filter();
  inline void clear_has_tail_filter();
  inline void set_has_replica();
  inline void clear_has_replica();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::ps::TailKeyIFilter* tail_filter_;
  ::google::protobuf::RepeatedPtrField< ::ps::Timestamp > backup_;
  bool push_;
  bool dyn_val_size_;
  bool replica_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fparam_2eproto();
  friend void protobuf_AssignDesc_proto_2fparam_2eproto();
  friend void protobuf_ShutdownFile_proto_2fparam_2eproto();

  void InitAsDefaultInstance();
  static ParamCall* default_instance_;
};
// -------------------------------------------------------------------

class ParamInitConfig : public ::google::protobuf::Message {
 public:
  ParamInitConfig();
  virtual ~ParamInitConfig();

  ParamInitConfig(const ParamInitConfig& from);

  inline ParamInitConfig& operator=(const ParamInitConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ParamInitConfig& default_instance();

  void Swap(ParamInitConfig* other);

  // implements Message ----------------------------------------------

  ParamInitConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ParamInitConfig& from);
  void MergeFrom(const ParamInitConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ParamInitConfig_Type Type;
  static const Type ZERO = ParamInitConfig_Type_ZERO;
  static const Type CONSTANT = ParamInitConfig_Type_CONSTANT;
  static const Type GAUSSIAN = ParamInitConfig_Type_GAUSSIAN;
  static const Type FILE = ParamInitConfig_Type_FILE;
  static const Type CLONE = ParamInitConfig_Type_CLONE;
  static inline bool Type_IsValid(int value) {
    return ParamInitConfig_Type_IsValid(value);
  }
  static const Type Type_MIN =
    ParamInitConfig_Type_Type_MIN;
  static const Type Type_MAX =
    ParamInitConfig_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    ParamInitConfig_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return ParamInitConfig_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return ParamInitConfig_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return ParamInitConfig_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .ps.ParamInitConfig.Type type = 1 [default = ZERO];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::ps::ParamInitConfig_Type type() const;
  inline void set_type(::ps::ParamInitConfig_Type value);

  // optional double constant = 2 [default = 1];
  inline bool has_constant() const;
  inline void clear_constant();
  static const int kConstantFieldNumber = 2;
  inline double constant() const;
  inline void set_constant(double value);

  // optional double mean = 3 [default = 0];
  inline bool has_mean() const;
  inline void clear_mean();
  static const int kMeanFieldNumber = 3;
  inline double mean() const;
  inline void set_mean(double value);

  // optional double std = 4 [default = 1];
  inline bool has_std() const;
  inline void clear_std();
  static const int kStdFieldNumber = 4;
  inline double std() const;
  inline void set_std(double value);

  // optional string file_name = 5;
  inline bool has_file_name() const;
  inline void clear_file_name();
  static const int kFileNameFieldNumber = 5;
  inline const ::std::string& file_name() const;
  inline void set_file_name(const ::std::string& value);
  inline void set_file_name(const char* value);
  inline void set_file_name(const char* value, size_t size);
  inline ::std::string* mutable_file_name();
  inline ::std::string* release_file_name();
  inline void set_allocated_file_name(::std::string* file_name);

  // @@protoc_insertion_point(class_scope:ps.ParamInitConfig)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_constant();
  inline void clear_has_constant();
  inline void set_has_mean();
  inline void clear_has_mean();
  inline void set_has_std();
  inline void clear_has_std();
  inline void set_has_file_name();
  inline void clear_has_file_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double constant_;
  double mean_;
  double std_;
  ::std::string* file_name_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fparam_2eproto();
  friend void protobuf_AssignDesc_proto_2fparam_2eproto();
  friend void protobuf_ShutdownFile_proto_2fparam_2eproto();

  void InitAsDefaultInstance();
  static ParamInitConfig* default_instance_;
};
// -------------------------------------------------------------------

class Timestamp : public ::google::protobuf::Message {
 public:
  Timestamp();
  virtual ~Timestamp();

  Timestamp(const Timestamp& from);

  inline Timestamp& operator=(const Timestamp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Timestamp& default_instance();

  void Swap(Timestamp* other);

  // implements Message ----------------------------------------------

  Timestamp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Timestamp& from);
  void MergeFrom(const Timestamp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string sender = 1;
  inline bool has_sender() const;
  inline void clear_sender();
  static const int kSenderFieldNumber = 1;
  inline const ::std::string& sender() const;
  inline void set_sender(const ::std::string& value);
  inline void set_sender(const char* value);
  inline void set_sender(const char* value, size_t size);
  inline ::std::string* mutable_sender();
  inline ::std::string* release_sender();
  inline void set_allocated_sender(::std::string* sender);

  // required int32 time = 2;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 2;
  inline ::google::protobuf::int32 time() const;
  inline void set_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ps.Timestamp)
 private:
  inline void set_has_sender();
  inline void clear_has_sender();
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* sender_;
  ::google::protobuf::int32 time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fparam_2eproto();
  friend void protobuf_AssignDesc_proto_2fparam_2eproto();
  friend void protobuf_ShutdownFile_proto_2fparam_2eproto();

  void InitAsDefaultInstance();
  static Timestamp* default_instance_;
};
// -------------------------------------------------------------------

class TailKeyIFilter : public ::google::protobuf::Message {
 public:
  TailKeyIFilter();
  virtual ~TailKeyIFilter();

  TailKeyIFilter(const TailKeyIFilter& from);

  inline TailKeyIFilter& operator=(const TailKeyIFilter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TailKeyIFilter& default_instance();

  void Swap(TailKeyIFilter* other);

  // implements Message ----------------------------------------------

  TailKeyIFilter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TailKeyIFilter& from);
  void MergeFrom(const TailKeyIFilter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool insert_count = 1;
  inline bool has_insert_count() const;
  inline void clear_insert_count();
  static const int kInsertCountFieldNumber = 1;
  inline bool insert_count() const;
  inline void set_insert_count(bool value);

  // optional int32 freq_threshold = 2;
  inline bool has_freq_threshold() const;
  inline void clear_freq_threshold();
  static const int kFreqThresholdFieldNumber = 2;
  inline ::google::protobuf::int32 freq_threshold() const;
  inline void set_freq_threshold(::google::protobuf::int32 value);

  // optional bool query_value = 3;
  inline bool has_query_value() const;
  inline void clear_query_value();
  static const int kQueryValueFieldNumber = 3;
  inline bool query_value() const;
  inline void set_query_value(bool value);

  // optional int32 countmin_n = 4 [default = 1000000];
  inline bool has_countmin_n() const;
  inline void clear_countmin_n();
  static const int kCountminNFieldNumber = 4;
  inline ::google::protobuf::int32 countmin_n() const;
  inline void set_countmin_n(::google::protobuf::int32 value);

  // optional int32 countmin_k = 5 [default = 2];
  inline bool has_countmin_k() const;
  inline void clear_countmin_k();
  static const int kCountminKFieldNumber = 5;
  inline ::google::protobuf::int32 countmin_k() const;
  inline void set_countmin_k(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ps.TailKeyIFilter)
 private:
  inline void set_has_insert_count();
  inline void clear_has_insert_count();
  inline void set_has_freq_threshold();
  inline void clear_has_freq_threshold();
  inline void set_has_query_value();
  inline void clear_has_query_value();
  inline void set_has_countmin_n();
  inline void clear_has_countmin_n();
  inline void set_has_countmin_k();
  inline void clear_has_countmin_k();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 freq_threshold_;
  bool insert_count_;
  bool query_value_;
  ::google::protobuf::int32 countmin_n_;
  ::google::protobuf::int32 countmin_k_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fparam_2eproto();
  friend void protobuf_AssignDesc_proto_2fparam_2eproto();
  friend void protobuf_ShutdownFile_proto_2fparam_2eproto();

  void InitAsDefaultInstance();
  static TailKeyIFilter* default_instance_;
};
// ===================================================================


// ===================================================================

// ParamCall

// optional bool push = 1 [default = true];
inline bool ParamCall::has_push() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParamCall::set_has_push() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParamCall::clear_has_push() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParamCall::clear_push() {
  push_ = true;
  clear_has_push();
}
inline bool ParamCall::push() const {
  return push_;
}
inline void ParamCall::set_push(bool value) {
  set_has_push();
  push_ = value;
}

// optional bool dyn_val_size = 4 [default = false];
inline bool ParamCall::has_dyn_val_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ParamCall::set_has_dyn_val_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ParamCall::clear_has_dyn_val_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ParamCall::clear_dyn_val_size() {
  dyn_val_size_ = false;
  clear_has_dyn_val_size();
}
inline bool ParamCall::dyn_val_size() const {
  return dyn_val_size_;
}
inline void ParamCall::set_dyn_val_size(bool value) {
  set_has_dyn_val_size();
  dyn_val_size_ = value;
}

// optional .ps.TailKeyIFilter tail_filter = 3;
inline bool ParamCall::has_tail_filter() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ParamCall::set_has_tail_filter() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ParamCall::clear_has_tail_filter() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ParamCall::clear_tail_filter() {
  if (tail_filter_ != NULL) tail_filter_->::ps::TailKeyIFilter::Clear();
  clear_has_tail_filter();
}
inline const ::ps::TailKeyIFilter& ParamCall::tail_filter() const {
  return tail_filter_ != NULL ? *tail_filter_ : *default_instance_->tail_filter_;
}
inline ::ps::TailKeyIFilter* ParamCall::mutable_tail_filter() {
  set_has_tail_filter();
  if (tail_filter_ == NULL) tail_filter_ = new ::ps::TailKeyIFilter;
  return tail_filter_;
}
inline ::ps::TailKeyIFilter* ParamCall::release_tail_filter() {
  clear_has_tail_filter();
  ::ps::TailKeyIFilter* temp = tail_filter_;
  tail_filter_ = NULL;
  return temp;
}
inline void ParamCall::set_allocated_tail_filter(::ps::TailKeyIFilter* tail_filter) {
  delete tail_filter_;
  tail_filter_ = tail_filter;
  if (tail_filter) {
    set_has_tail_filter();
  } else {
    clear_has_tail_filter();
  }
}

// optional bool replica = 10;
inline bool ParamCall::has_replica() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ParamCall::set_has_replica() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ParamCall::clear_has_replica() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ParamCall::clear_replica() {
  replica_ = false;
  clear_has_replica();
}
inline bool ParamCall::replica() const {
  return replica_;
}
inline void ParamCall::set_replica(bool value) {
  set_has_replica();
  replica_ = value;
}

// repeated .ps.Timestamp backup = 11;
inline int ParamCall::backup_size() const {
  return backup_.size();
}
inline void ParamCall::clear_backup() {
  backup_.Clear();
}
inline const ::ps::Timestamp& ParamCall::backup(int index) const {
  return backup_.Get(index);
}
inline ::ps::Timestamp* ParamCall::mutable_backup(int index) {
  return backup_.Mutable(index);
}
inline ::ps::Timestamp* ParamCall::add_backup() {
  return backup_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ps::Timestamp >&
ParamCall::backup() const {
  return backup_;
}
inline ::google::protobuf::RepeatedPtrField< ::ps::Timestamp >*
ParamCall::mutable_backup() {
  return &backup_;
}

// -------------------------------------------------------------------

// ParamInitConfig

// optional .ps.ParamInitConfig.Type type = 1 [default = ZERO];
inline bool ParamInitConfig::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParamInitConfig::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParamInitConfig::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParamInitConfig::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::ps::ParamInitConfig_Type ParamInitConfig::type() const {
  return static_cast< ::ps::ParamInitConfig_Type >(type_);
}
inline void ParamInitConfig::set_type(::ps::ParamInitConfig_Type value) {
  assert(::ps::ParamInitConfig_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional double constant = 2 [default = 1];
inline bool ParamInitConfig::has_constant() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ParamInitConfig::set_has_constant() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ParamInitConfig::clear_has_constant() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ParamInitConfig::clear_constant() {
  constant_ = 1;
  clear_has_constant();
}
inline double ParamInitConfig::constant() const {
  return constant_;
}
inline void ParamInitConfig::set_constant(double value) {
  set_has_constant();
  constant_ = value;
}

// optional double mean = 3 [default = 0];
inline bool ParamInitConfig::has_mean() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ParamInitConfig::set_has_mean() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ParamInitConfig::clear_has_mean() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ParamInitConfig::clear_mean() {
  mean_ = 0;
  clear_has_mean();
}
inline double ParamInitConfig::mean() const {
  return mean_;
}
inline void ParamInitConfig::set_mean(double value) {
  set_has_mean();
  mean_ = value;
}

// optional double std = 4 [default = 1];
inline bool ParamInitConfig::has_std() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ParamInitConfig::set_has_std() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ParamInitConfig::clear_has_std() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ParamInitConfig::clear_std() {
  std_ = 1;
  clear_has_std();
}
inline double ParamInitConfig::std() const {
  return std_;
}
inline void ParamInitConfig::set_std(double value) {
  set_has_std();
  std_ = value;
}

// optional string file_name = 5;
inline bool ParamInitConfig::has_file_name() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ParamInitConfig::set_has_file_name() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ParamInitConfig::clear_has_file_name() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ParamInitConfig::clear_file_name() {
  if (file_name_ != &::google::protobuf::internal::kEmptyString) {
    file_name_->clear();
  }
  clear_has_file_name();
}
inline const ::std::string& ParamInitConfig::file_name() const {
  return *file_name_;
}
inline void ParamInitConfig::set_file_name(const ::std::string& value) {
  set_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    file_name_ = new ::std::string;
  }
  file_name_->assign(value);
}
inline void ParamInitConfig::set_file_name(const char* value) {
  set_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    file_name_ = new ::std::string;
  }
  file_name_->assign(value);
}
inline void ParamInitConfig::set_file_name(const char* value, size_t size) {
  set_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    file_name_ = new ::std::string;
  }
  file_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ParamInitConfig::mutable_file_name() {
  set_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    file_name_ = new ::std::string;
  }
  return file_name_;
}
inline ::std::string* ParamInitConfig::release_file_name() {
  clear_has_file_name();
  if (file_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = file_name_;
    file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ParamInitConfig::set_allocated_file_name(::std::string* file_name) {
  if (file_name_ != &::google::protobuf::internal::kEmptyString) {
    delete file_name_;
  }
  if (file_name) {
    set_has_file_name();
    file_name_ = file_name;
  } else {
    clear_has_file_name();
    file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// Timestamp

// required string sender = 1;
inline bool Timestamp::has_sender() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Timestamp::set_has_sender() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Timestamp::clear_has_sender() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Timestamp::clear_sender() {
  if (sender_ != &::google::protobuf::internal::kEmptyString) {
    sender_->clear();
  }
  clear_has_sender();
}
inline const ::std::string& Timestamp::sender() const {
  return *sender_;
}
inline void Timestamp::set_sender(const ::std::string& value) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
}
inline void Timestamp::set_sender(const char* value) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
}
inline void Timestamp::set_sender(const char* value, size_t size) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  sender_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Timestamp::mutable_sender() {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  return sender_;
}
inline ::std::string* Timestamp::release_sender() {
  clear_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sender_;
    sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Timestamp::set_allocated_sender(::std::string* sender) {
  if (sender_ != &::google::protobuf::internal::kEmptyString) {
    delete sender_;
  }
  if (sender) {
    set_has_sender();
    sender_ = sender;
  } else {
    clear_has_sender();
    sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 time = 2;
inline bool Timestamp::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Timestamp::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Timestamp::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Timestamp::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 Timestamp::time() const {
  return time_;
}
inline void Timestamp::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
}

// -------------------------------------------------------------------

// TailKeyIFilter

// optional bool insert_count = 1;
inline bool TailKeyIFilter::has_insert_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TailKeyIFilter::set_has_insert_count() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TailKeyIFilter::clear_has_insert_count() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TailKeyIFilter::clear_insert_count() {
  insert_count_ = false;
  clear_has_insert_count();
}
inline bool TailKeyIFilter::insert_count() const {
  return insert_count_;
}
inline void TailKeyIFilter::set_insert_count(bool value) {
  set_has_insert_count();
  insert_count_ = value;
}

// optional int32 freq_threshold = 2;
inline bool TailKeyIFilter::has_freq_threshold() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TailKeyIFilter::set_has_freq_threshold() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TailKeyIFilter::clear_has_freq_threshold() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TailKeyIFilter::clear_freq_threshold() {
  freq_threshold_ = 0;
  clear_has_freq_threshold();
}
inline ::google::protobuf::int32 TailKeyIFilter::freq_threshold() const {
  return freq_threshold_;
}
inline void TailKeyIFilter::set_freq_threshold(::google::protobuf::int32 value) {
  set_has_freq_threshold();
  freq_threshold_ = value;
}

// optional bool query_value = 3;
inline bool TailKeyIFilter::has_query_value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TailKeyIFilter::set_has_query_value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TailKeyIFilter::clear_has_query_value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TailKeyIFilter::clear_query_value() {
  query_value_ = false;
  clear_has_query_value();
}
inline bool TailKeyIFilter::query_value() const {
  return query_value_;
}
inline void TailKeyIFilter::set_query_value(bool value) {
  set_has_query_value();
  query_value_ = value;
}

// optional int32 countmin_n = 4 [default = 1000000];
inline bool TailKeyIFilter::has_countmin_n() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TailKeyIFilter::set_has_countmin_n() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TailKeyIFilter::clear_has_countmin_n() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TailKeyIFilter::clear_countmin_n() {
  countmin_n_ = 1000000;
  clear_has_countmin_n();
}
inline ::google::protobuf::int32 TailKeyIFilter::countmin_n() const {
  return countmin_n_;
}
inline void TailKeyIFilter::set_countmin_n(::google::protobuf::int32 value) {
  set_has_countmin_n();
  countmin_n_ = value;
}

// optional int32 countmin_k = 5 [default = 2];
inline bool TailKeyIFilter::has_countmin_k() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TailKeyIFilter::set_has_countmin_k() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TailKeyIFilter::clear_has_countmin_k() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TailKeyIFilter::clear_countmin_k() {
  countmin_k_ = 2;
  clear_has_countmin_k();
}
inline ::google::protobuf::int32 TailKeyIFilter::countmin_k() const {
  return countmin_k_;
}
inline void TailKeyIFilter::set_countmin_k(::google::protobuf::int32 value) {
  set_has_countmin_k();
  countmin_k_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ps

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ps::ParamInitConfig_Type>() {
  return ::ps::ParamInitConfig_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fparam_2eproto__INCLUDED
