// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/param.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto/param.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ps {

namespace {

const ::google::protobuf::Descriptor* ParamCall_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ParamCall_reflection_ = NULL;
const ::google::protobuf::Descriptor* ParamInitConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ParamInitConfig_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ParamInitConfig_Type_descriptor_ = NULL;
const ::google::protobuf::Descriptor* Timestamp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Timestamp_reflection_ = NULL;
const ::google::protobuf::Descriptor* TailKeyIFilter_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TailKeyIFilter_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_2fparam_2eproto() {
  protobuf_AddDesc_proto_2fparam_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto/param.proto");
  GOOGLE_CHECK(file != NULL);
  ParamCall_descriptor_ = file->message_type(0);
  static const int ParamCall_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamCall, push_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamCall, dyn_val_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamCall, tail_filter_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamCall, replica_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamCall, backup_),
  };
  ParamCall_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ParamCall_descriptor_,
      ParamCall::default_instance_,
      ParamCall_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamCall, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamCall, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ParamCall));
  ParamInitConfig_descriptor_ = file->message_type(1);
  static const int ParamInitConfig_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamInitConfig, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamInitConfig, constant_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamInitConfig, mean_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamInitConfig, std_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamInitConfig, file_name_),
  };
  ParamInitConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ParamInitConfig_descriptor_,
      ParamInitConfig::default_instance_,
      ParamInitConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamInitConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamInitConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ParamInitConfig));
  ParamInitConfig_Type_descriptor_ = ParamInitConfig_descriptor_->enum_type(0);
  Timestamp_descriptor_ = file->message_type(2);
  static const int Timestamp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Timestamp, sender_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Timestamp, time_),
  };
  Timestamp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Timestamp_descriptor_,
      Timestamp::default_instance_,
      Timestamp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Timestamp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Timestamp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Timestamp));
  TailKeyIFilter_descriptor_ = file->message_type(3);
  static const int TailKeyIFilter_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TailKeyIFilter, insert_count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TailKeyIFilter, freq_threshold_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TailKeyIFilter, query_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TailKeyIFilter, countmin_n_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TailKeyIFilter, countmin_k_),
  };
  TailKeyIFilter_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TailKeyIFilter_descriptor_,
      TailKeyIFilter::default_instance_,
      TailKeyIFilter_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TailKeyIFilter, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TailKeyIFilter, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TailKeyIFilter));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_2fparam_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ParamCall_descriptor_, &ParamCall::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ParamInitConfig_descriptor_, &ParamInitConfig::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Timestamp_descriptor_, &Timestamp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TailKeyIFilter_descriptor_, &TailKeyIFilter::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_2fparam_2eproto() {
  delete ParamCall::default_instance_;
  delete ParamCall_reflection_;
  delete ParamInitConfig::default_instance_;
  delete ParamInitConfig_reflection_;
  delete Timestamp::default_instance_;
  delete Timestamp_reflection_;
  delete TailKeyIFilter::default_instance_;
  delete TailKeyIFilter_reflection_;
}

void protobuf_AddDesc_proto_2fparam_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021proto/param.proto\022\002ps\"\225\001\n\tParamCall\022\022\n"
    "\004push\030\001 \001(\010:\004true\022\033\n\014dyn_val_size\030\004 \001(\010:"
    "\005false\022\'\n\013tail_filter\030\003 \001(\0132\022.ps.TailKey"
    "IFilter\022\017\n\007replica\030\n \001(\010\022\035\n\006backup\030\013 \003(\013"
    "2\r.ps.Timestamp\"\313\001\n\017ParamInitConfig\022,\n\004t"
    "ype\030\001 \001(\0162\030.ps.ParamInitConfig.Type:\004ZER"
    "O\022\023\n\010constant\030\002 \001(\001:\0011\022\017\n\004mean\030\003 \001(\001:\0010\022"
    "\016\n\003std\030\004 \001(\001:\0011\022\021\n\tfile_name\030\005 \001(\t\"A\n\004Ty"
    "pe\022\010\n\004ZERO\020\001\022\014\n\010CONSTANT\020\002\022\014\n\010GAUSSIAN\020\003"
    "\022\010\n\004FILE\020\004\022\t\n\005CLONE\020\005\")\n\tTimestamp\022\016\n\006se"
    "nder\030\001 \002(\t\022\014\n\004time\030\002 \002(\005\"\207\001\n\016TailKeyIFil"
    "ter\022\024\n\014insert_count\030\001 \001(\010\022\026\n\016freq_thresh"
    "old\030\002 \001(\005\022\023\n\013query_value\030\003 \001(\010\022\033\n\ncountm"
    "in_n\030\004 \001(\005:\0071000000\022\025\n\ncountmin_k\030\005 \001(\005:"
    "\0012", 562);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/param.proto", &protobuf_RegisterTypes);
  ParamCall::default_instance_ = new ParamCall();
  ParamInitConfig::default_instance_ = new ParamInitConfig();
  Timestamp::default_instance_ = new Timestamp();
  TailKeyIFilter::default_instance_ = new TailKeyIFilter();
  ParamCall::default_instance_->InitAsDefaultInstance();
  ParamInitConfig::default_instance_->InitAsDefaultInstance();
  Timestamp::default_instance_->InitAsDefaultInstance();
  TailKeyIFilter::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_2fparam_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_2fparam_2eproto {
  StaticDescriptorInitializer_proto_2fparam_2eproto() {
    protobuf_AddDesc_proto_2fparam_2eproto();
  }
} static_descriptor_initializer_proto_2fparam_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ParamCall::kPushFieldNumber;
const int ParamCall::kDynValSizeFieldNumber;
const int ParamCall::kTailFilterFieldNumber;
const int ParamCall::kReplicaFieldNumber;
const int ParamCall::kBackupFieldNumber;
#endif  // !_MSC_VER

ParamCall::ParamCall()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ParamCall::InitAsDefaultInstance() {
  tail_filter_ = const_cast< ::ps::TailKeyIFilter*>(&::ps::TailKeyIFilter::default_instance());
}

ParamCall::ParamCall(const ParamCall& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ParamCall::SharedCtor() {
  _cached_size_ = 0;
  push_ = true;
  dyn_val_size_ = false;
  tail_filter_ = NULL;
  replica_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ParamCall::~ParamCall() {
  SharedDtor();
}

void ParamCall::SharedDtor() {
  if (this != default_instance_) {
    delete tail_filter_;
  }
}

void ParamCall::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParamCall::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ParamCall_descriptor_;
}

const ParamCall& ParamCall::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2fparam_2eproto();
  return *default_instance_;
}

ParamCall* ParamCall::default_instance_ = NULL;

ParamCall* ParamCall::New() const {
  return new ParamCall;
}

void ParamCall::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    push_ = true;
    dyn_val_size_ = false;
    if (has_tail_filter()) {
      if (tail_filter_ != NULL) tail_filter_->::ps::TailKeyIFilter::Clear();
    }
    replica_ = false;
  }
  backup_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ParamCall::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool push = 1 [default = true];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &push_)));
          set_has_push();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_tail_filter;
        break;
      }

      // optional .ps.TailKeyIFilter tail_filter = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_tail_filter:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_tail_filter()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_dyn_val_size;
        break;
      }

      // optional bool dyn_val_size = 4 [default = false];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_dyn_val_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &dyn_val_size_)));
          set_has_dyn_val_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_replica;
        break;
      }

      // optional bool replica = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_replica:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &replica_)));
          set_has_replica();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_backup;
        break;
      }

      // repeated .ps.Timestamp backup = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_backup:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_backup()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_backup;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ParamCall::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool push = 1 [default = true];
  if (has_push()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->push(), output);
  }

  // optional .ps.TailKeyIFilter tail_filter = 3;
  if (has_tail_filter()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->tail_filter(), output);
  }

  // optional bool dyn_val_size = 4 [default = false];
  if (has_dyn_val_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->dyn_val_size(), output);
  }

  // optional bool replica = 10;
  if (has_replica()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->replica(), output);
  }

  // repeated .ps.Timestamp backup = 11;
  for (int i = 0; i < this->backup_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->backup(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ParamCall::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool push = 1 [default = true];
  if (has_push()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->push(), target);
  }

  // optional .ps.TailKeyIFilter tail_filter = 3;
  if (has_tail_filter()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->tail_filter(), target);
  }

  // optional bool dyn_val_size = 4 [default = false];
  if (has_dyn_val_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->dyn_val_size(), target);
  }

  // optional bool replica = 10;
  if (has_replica()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->replica(), target);
  }

  // repeated .ps.Timestamp backup = 11;
  for (int i = 0; i < this->backup_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, this->backup(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ParamCall::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool push = 1 [default = true];
    if (has_push()) {
      total_size += 1 + 1;
    }

    // optional bool dyn_val_size = 4 [default = false];
    if (has_dyn_val_size()) {
      total_size += 1 + 1;
    }

    // optional .ps.TailKeyIFilter tail_filter = 3;
    if (has_tail_filter()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->tail_filter());
    }

    // optional bool replica = 10;
    if (has_replica()) {
      total_size += 1 + 1;
    }

  }
  // repeated .ps.Timestamp backup = 11;
  total_size += 1 * this->backup_size();
  for (int i = 0; i < this->backup_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->backup(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParamCall::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ParamCall* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ParamCall*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ParamCall::MergeFrom(const ParamCall& from) {
  GOOGLE_CHECK_NE(&from, this);
  backup_.MergeFrom(from.backup_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_push()) {
      set_push(from.push());
    }
    if (from.has_dyn_val_size()) {
      set_dyn_val_size(from.dyn_val_size());
    }
    if (from.has_tail_filter()) {
      mutable_tail_filter()->::ps::TailKeyIFilter::MergeFrom(from.tail_filter());
    }
    if (from.has_replica()) {
      set_replica(from.replica());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ParamCall::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParamCall::CopyFrom(const ParamCall& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParamCall::IsInitialized() const {

  for (int i = 0; i < backup_size(); i++) {
    if (!this->backup(i).IsInitialized()) return false;
  }
  return true;
}

void ParamCall::Swap(ParamCall* other) {
  if (other != this) {
    std::swap(push_, other->push_);
    std::swap(dyn_val_size_, other->dyn_val_size_);
    std::swap(tail_filter_, other->tail_filter_);
    std::swap(replica_, other->replica_);
    backup_.Swap(&other->backup_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ParamCall::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ParamCall_descriptor_;
  metadata.reflection = ParamCall_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* ParamInitConfig_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ParamInitConfig_Type_descriptor_;
}
bool ParamInitConfig_Type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ParamInitConfig_Type ParamInitConfig::ZERO;
const ParamInitConfig_Type ParamInitConfig::CONSTANT;
const ParamInitConfig_Type ParamInitConfig::GAUSSIAN;
const ParamInitConfig_Type ParamInitConfig::FILE;
const ParamInitConfig_Type ParamInitConfig::CLONE;
const ParamInitConfig_Type ParamInitConfig::Type_MIN;
const ParamInitConfig_Type ParamInitConfig::Type_MAX;
const int ParamInitConfig::Type_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ParamInitConfig::kTypeFieldNumber;
const int ParamInitConfig::kConstantFieldNumber;
const int ParamInitConfig::kMeanFieldNumber;
const int ParamInitConfig::kStdFieldNumber;
const int ParamInitConfig::kFileNameFieldNumber;
#endif  // !_MSC_VER

ParamInitConfig::ParamInitConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ParamInitConfig::InitAsDefaultInstance() {
}

ParamInitConfig::ParamInitConfig(const ParamInitConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ParamInitConfig::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  constant_ = 1;
  mean_ = 0;
  std_ = 1;
  file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ParamInitConfig::~ParamInitConfig() {
  SharedDtor();
}

void ParamInitConfig::SharedDtor() {
  if (file_name_ != &::google::protobuf::internal::kEmptyString) {
    delete file_name_;
  }
  if (this != default_instance_) {
  }
}

void ParamInitConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParamInitConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ParamInitConfig_descriptor_;
}

const ParamInitConfig& ParamInitConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2fparam_2eproto();
  return *default_instance_;
}

ParamInitConfig* ParamInitConfig::default_instance_ = NULL;

ParamInitConfig* ParamInitConfig::New() const {
  return new ParamInitConfig;
}

void ParamInitConfig::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    constant_ = 1;
    mean_ = 0;
    std_ = 1;
    if (has_file_name()) {
      if (file_name_ != &::google::protobuf::internal::kEmptyString) {
        file_name_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ParamInitConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .ps.ParamInitConfig.Type type = 1 [default = ZERO];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ps::ParamInitConfig_Type_IsValid(value)) {
            set_type(static_cast< ::ps::ParamInitConfig_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_constant;
        break;
      }

      // optional double constant = 2 [default = 1];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_constant:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &constant_)));
          set_has_constant();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(25)) goto parse_mean;
        break;
      }

      // optional double mean = 3 [default = 0];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_mean:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &mean_)));
          set_has_mean();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(33)) goto parse_std;
        break;
      }

      // optional double std = 4 [default = 1];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_std:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &std_)));
          set_has_std();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_file_name;
        break;
      }

      // optional string file_name = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_file_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_file_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->file_name().data(), this->file_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ParamInitConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .ps.ParamInitConfig.Type type = 1 [default = ZERO];
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional double constant = 2 [default = 1];
  if (has_constant()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->constant(), output);
  }

  // optional double mean = 3 [default = 0];
  if (has_mean()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->mean(), output);
  }

  // optional double std = 4 [default = 1];
  if (has_std()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->std(), output);
  }

  // optional string file_name = 5;
  if (has_file_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->file_name().data(), this->file_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->file_name(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ParamInitConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .ps.ParamInitConfig.Type type = 1 [default = ZERO];
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional double constant = 2 [default = 1];
  if (has_constant()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->constant(), target);
  }

  // optional double mean = 3 [default = 0];
  if (has_mean()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->mean(), target);
  }

  // optional double std = 4 [default = 1];
  if (has_std()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->std(), target);
  }

  // optional string file_name = 5;
  if (has_file_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->file_name().data(), this->file_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->file_name(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ParamInitConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .ps.ParamInitConfig.Type type = 1 [default = ZERO];
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional double constant = 2 [default = 1];
    if (has_constant()) {
      total_size += 1 + 8;
    }

    // optional double mean = 3 [default = 0];
    if (has_mean()) {
      total_size += 1 + 8;
    }

    // optional double std = 4 [default = 1];
    if (has_std()) {
      total_size += 1 + 8;
    }

    // optional string file_name = 5;
    if (has_file_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->file_name());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParamInitConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ParamInitConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ParamInitConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ParamInitConfig::MergeFrom(const ParamInitConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_constant()) {
      set_constant(from.constant());
    }
    if (from.has_mean()) {
      set_mean(from.mean());
    }
    if (from.has_std()) {
      set_std(from.std());
    }
    if (from.has_file_name()) {
      set_file_name(from.file_name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ParamInitConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParamInitConfig::CopyFrom(const ParamInitConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParamInitConfig::IsInitialized() const {

  return true;
}

void ParamInitConfig::Swap(ParamInitConfig* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(constant_, other->constant_);
    std::swap(mean_, other->mean_);
    std::swap(std_, other->std_);
    std::swap(file_name_, other->file_name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ParamInitConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ParamInitConfig_descriptor_;
  metadata.reflection = ParamInitConfig_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Timestamp::kSenderFieldNumber;
const int Timestamp::kTimeFieldNumber;
#endif  // !_MSC_VER

Timestamp::Timestamp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Timestamp::InitAsDefaultInstance() {
}

Timestamp::Timestamp(const Timestamp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Timestamp::SharedCtor() {
  _cached_size_ = 0;
  sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  time_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Timestamp::~Timestamp() {
  SharedDtor();
}

void Timestamp::SharedDtor() {
  if (sender_ != &::google::protobuf::internal::kEmptyString) {
    delete sender_;
  }
  if (this != default_instance_) {
  }
}

void Timestamp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Timestamp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Timestamp_descriptor_;
}

const Timestamp& Timestamp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2fparam_2eproto();
  return *default_instance_;
}

Timestamp* Timestamp::default_instance_ = NULL;

Timestamp* Timestamp::New() const {
  return new Timestamp;
}

void Timestamp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_sender()) {
      if (sender_ != &::google::protobuf::internal::kEmptyString) {
        sender_->clear();
      }
    }
    time_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Timestamp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string sender = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sender()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->sender().data(), this->sender().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_time;
        break;
      }

      // required int32 time = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &time_)));
          set_has_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Timestamp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string sender = 1;
  if (has_sender()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sender().data(), this->sender().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->sender(), output);
  }

  // required int32 time = 2;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->time(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Timestamp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string sender = 1;
  if (has_sender()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sender().data(), this->sender().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->sender(), target);
  }

  // required int32 time = 2;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->time(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Timestamp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string sender = 1;
    if (has_sender()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sender());
    }

    // required int32 time = 2;
    if (has_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->time());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Timestamp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Timestamp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Timestamp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Timestamp::MergeFrom(const Timestamp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_sender()) {
      set_sender(from.sender());
    }
    if (from.has_time()) {
      set_time(from.time());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Timestamp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Timestamp::CopyFrom(const Timestamp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Timestamp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Timestamp::Swap(Timestamp* other) {
  if (other != this) {
    std::swap(sender_, other->sender_);
    std::swap(time_, other->time_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Timestamp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Timestamp_descriptor_;
  metadata.reflection = Timestamp_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TailKeyIFilter::kInsertCountFieldNumber;
const int TailKeyIFilter::kFreqThresholdFieldNumber;
const int TailKeyIFilter::kQueryValueFieldNumber;
const int TailKeyIFilter::kCountminNFieldNumber;
const int TailKeyIFilter::kCountminKFieldNumber;
#endif  // !_MSC_VER

TailKeyIFilter::TailKeyIFilter()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TailKeyIFilter::InitAsDefaultInstance() {
}

TailKeyIFilter::TailKeyIFilter(const TailKeyIFilter& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TailKeyIFilter::SharedCtor() {
  _cached_size_ = 0;
  insert_count_ = false;
  freq_threshold_ = 0;
  query_value_ = false;
  countmin_n_ = 1000000;
  countmin_k_ = 2;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TailKeyIFilter::~TailKeyIFilter() {
  SharedDtor();
}

void TailKeyIFilter::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TailKeyIFilter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TailKeyIFilter::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TailKeyIFilter_descriptor_;
}

const TailKeyIFilter& TailKeyIFilter::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2fparam_2eproto();
  return *default_instance_;
}

TailKeyIFilter* TailKeyIFilter::default_instance_ = NULL;

TailKeyIFilter* TailKeyIFilter::New() const {
  return new TailKeyIFilter;
}

void TailKeyIFilter::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    insert_count_ = false;
    freq_threshold_ = 0;
    query_value_ = false;
    countmin_n_ = 1000000;
    countmin_k_ = 2;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TailKeyIFilter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool insert_count = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &insert_count_)));
          set_has_insert_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_freq_threshold;
        break;
      }

      // optional int32 freq_threshold = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_freq_threshold:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &freq_threshold_)));
          set_has_freq_threshold();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_query_value;
        break;
      }

      // optional bool query_value = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_query_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &query_value_)));
          set_has_query_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_countmin_n;
        break;
      }

      // optional int32 countmin_n = 4 [default = 1000000];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_countmin_n:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &countmin_n_)));
          set_has_countmin_n();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_countmin_k;
        break;
      }

      // optional int32 countmin_k = 5 [default = 2];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_countmin_k:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &countmin_k_)));
          set_has_countmin_k();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TailKeyIFilter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool insert_count = 1;
  if (has_insert_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->insert_count(), output);
  }

  // optional int32 freq_threshold = 2;
  if (has_freq_threshold()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->freq_threshold(), output);
  }

  // optional bool query_value = 3;
  if (has_query_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->query_value(), output);
  }

  // optional int32 countmin_n = 4 [default = 1000000];
  if (has_countmin_n()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->countmin_n(), output);
  }

  // optional int32 countmin_k = 5 [default = 2];
  if (has_countmin_k()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->countmin_k(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TailKeyIFilter::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool insert_count = 1;
  if (has_insert_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->insert_count(), target);
  }

  // optional int32 freq_threshold = 2;
  if (has_freq_threshold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->freq_threshold(), target);
  }

  // optional bool query_value = 3;
  if (has_query_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->query_value(), target);
  }

  // optional int32 countmin_n = 4 [default = 1000000];
  if (has_countmin_n()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->countmin_n(), target);
  }

  // optional int32 countmin_k = 5 [default = 2];
  if (has_countmin_k()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->countmin_k(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TailKeyIFilter::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool insert_count = 1;
    if (has_insert_count()) {
      total_size += 1 + 1;
    }

    // optional int32 freq_threshold = 2;
    if (has_freq_threshold()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->freq_threshold());
    }

    // optional bool query_value = 3;
    if (has_query_value()) {
      total_size += 1 + 1;
    }

    // optional int32 countmin_n = 4 [default = 1000000];
    if (has_countmin_n()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->countmin_n());
    }

    // optional int32 countmin_k = 5 [default = 2];
    if (has_countmin_k()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->countmin_k());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TailKeyIFilter::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TailKeyIFilter* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TailKeyIFilter*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TailKeyIFilter::MergeFrom(const TailKeyIFilter& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_insert_count()) {
      set_insert_count(from.insert_count());
    }
    if (from.has_freq_threshold()) {
      set_freq_threshold(from.freq_threshold());
    }
    if (from.has_query_value()) {
      set_query_value(from.query_value());
    }
    if (from.has_countmin_n()) {
      set_countmin_n(from.countmin_n());
    }
    if (from.has_countmin_k()) {
      set_countmin_k(from.countmin_k());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TailKeyIFilter::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TailKeyIFilter::CopyFrom(const TailKeyIFilter& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TailKeyIFilter::IsInitialized() const {

  return true;
}

void TailKeyIFilter::Swap(TailKeyIFilter* other) {
  if (other != this) {
    std::swap(insert_count_, other->insert_count_);
    std::swap(freq_threshold_, other->freq_threshold_);
    std::swap(query_value_, other->query_value_);
    std::swap(countmin_n_, other->countmin_n_);
    std::swap(countmin_k_, other->countmin_k_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TailKeyIFilter::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TailKeyIFilter_descriptor_;
  metadata.reflection = TailKeyIFilter_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ps

// @@protoc_insertion_point(global_scope)
