// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/task.proto

#ifndef PROTOBUF_proto_2ftask_2eproto__INCLUDED
#define PROTOBUF_proto_2ftask_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto/range.pb.h"
#include "proto/data.pb.h"
#include "proto/node.pb.h"
#include "proto/param.pb.h"
#include "proto/filter.pb.h"
#include "proto/assign_op.pb.h"
// @@protoc_insertion_point(includes)

namespace ps {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2ftask_2eproto();
void protobuf_AssignDesc_proto_2ftask_2eproto();
void protobuf_ShutdownFile_proto_2ftask_2eproto();

class Task;
class Control;

enum Control_Command {
  Control_Command_REGISTER_NODE = 2,
  Control_Command_READY_TO_EXIT = 4,
  Control_Command_READY_TO_RUN = 5,
  Control_Command_ADD_NODE = 10,
  Control_Command_REMOVE_NODE = 13,
  Control_Command_EXIT = 14
};
bool Control_Command_IsValid(int value);
const Control_Command Control_Command_Command_MIN = Control_Command_REGISTER_NODE;
const Control_Command Control_Command_Command_MAX = Control_Command_EXIT;
const int Control_Command_Command_ARRAYSIZE = Control_Command_Command_MAX + 1;

const ::google::protobuf::EnumDescriptor* Control_Command_descriptor();
inline const ::std::string& Control_Command_Name(Control_Command value) {
  return ::google::protobuf::internal::NameOfEnum(
    Control_Command_descriptor(), value);
}
inline bool Control_Command_Parse(
    const ::std::string& name, Control_Command* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Control_Command>(
    Control_Command_descriptor(), name, value);
}
enum DataType {
  OTHER = 0,
  INT8 = 1,
  INT16 = 2,
  INT32 = 3,
  INT64 = 4,
  UINT8 = 5,
  UINT16 = 6,
  UINT32 = 7,
  UINT64 = 8,
  FLOAT = 9,
  DOUBLE = 10,
  CHAR = 11
};
bool DataType_IsValid(int value);
const DataType DataType_MIN = OTHER;
const DataType DataType_MAX = CHAR;
const int DataType_ARRAYSIZE = DataType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataType_descriptor();
inline const ::std::string& DataType_Name(DataType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataType_descriptor(), value);
}
inline bool DataType_Parse(
    const ::std::string& name, DataType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataType>(
    DataType_descriptor(), name, value);
}
// ===================================================================

class Task : public ::google::protobuf::Message {
 public:
  Task();
  virtual ~Task();

  Task(const Task& from);

  inline Task& operator=(const Task& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Task& default_instance();

  void Swap(Task* other);

  // implements Message ----------------------------------------------

  Task* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Task& from);
  void MergeFrom(const Task& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes msg = 17;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 17;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const void* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  inline void set_allocated_msg(::std::string* msg);

  // optional int32 cmd = 19 [default = 0];
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 19;
  inline ::google::protobuf::int32 cmd() const;
  inline void set_cmd(::google::protobuf::int32 value);

  // optional .ps.AsOp op = 21;
  inline bool has_op() const;
  inline void clear_op();
  static const int kOpFieldNumber = 21;
  inline ::ps::AsOp op() const;
  inline void set_op(::ps::AsOp value);

  // optional bool control = 1 [default = false];
  inline bool has_control() const;
  inline void clear_control();
  static const int kControlFieldNumber = 1;
  inline bool control() const;
  inline void set_control(bool value);

  // optional bool request = 2 [default = false];
  inline bool has_request() const;
  inline void clear_request();
  static const int kRequestFieldNumber = 2;
  inline bool request() const;
  inline void set_request(bool value);

  // optional int32 customer_id = 3;
  inline bool has_customer_id() const;
  inline void clear_customer_id();
  static const int kCustomerIdFieldNumber = 3;
  inline ::google::protobuf::int32 customer_id() const;
  inline void set_customer_id(::google::protobuf::int32 value);

  // optional int32 time = 5;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 5;
  inline ::google::protobuf::int32 time() const;
  inline void set_time(::google::protobuf::int32 value);

  // repeated int32 wait_time = 6;
  inline int wait_time_size() const;
  inline void clear_wait_time();
  static const int kWaitTimeFieldNumber = 6;
  inline ::google::protobuf::int32 wait_time(int index) const;
  inline void set_wait_time(int index, ::google::protobuf::int32 value);
  inline void add_wait_time(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      wait_time() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_wait_time();

  // optional .ps.PbRange key_range = 7;
  inline bool has_key_range() const;
  inline void clear_key_range();
  static const int kKeyRangeFieldNumber = 7;
  inline const ::ps::PbRange& key_range() const;
  inline ::ps::PbRange* mutable_key_range();
  inline ::ps::PbRange* release_key_range();
  inline void set_allocated_key_range(::ps::PbRange* key_range);

  // optional int32 key_channel = 8;
  inline bool has_key_channel() const;
  inline void clear_key_channel();
  static const int kKeyChannelFieldNumber = 8;
  inline ::google::protobuf::int32 key_channel() const;
  inline void set_key_channel(::google::protobuf::int32 value);

  // optional bool has_key = 9 [default = false];
  inline bool has_has_key() const;
  inline void clear_has_key();
  static const int kHasKeyFieldNumber = 9;
  inline bool has_key() const;
  inline void set_has_key(bool value);

  // optional .ps.DataType key_type = 13;
  inline bool has_key_type() const;
  inline void clear_key_type();
  static const int kKeyTypeFieldNumber = 13;
  inline ::ps::DataType key_type() const;
  inline void set_key_type(::ps::DataType value);

  // repeated .ps.DataType value_type = 14 [packed = true];
  inline int value_type_size() const;
  inline void clear_value_type();
  static const int kValueTypeFieldNumber = 14;
  inline ::ps::DataType value_type(int index) const;
  inline void set_value_type(int index, ::ps::DataType value);
  inline void add_value_type(::ps::DataType value);
  inline const ::google::protobuf::RepeatedField<int>& value_type() const;
  inline ::google::protobuf::RepeatedField<int>* mutable_value_type();

  // repeated .ps.Filter filter = 12;
  inline int filter_size() const;
  inline void clear_filter();
  static const int kFilterFieldNumber = 12;
  inline const ::ps::Filter& filter(int index) const;
  inline ::ps::Filter* mutable_filter(int index);
  inline ::ps::Filter* add_filter();
  inline const ::google::protobuf::RepeatedPtrField< ::ps::Filter >&
      filter() const;
  inline ::google::protobuf::RepeatedPtrField< ::ps::Filter >*
      mutable_filter();

  // optional .ps.Control ctrl = 18;
  inline bool has_ctrl() const;
  inline void clear_ctrl();
  static const int kCtrlFieldNumber = 18;
  inline const ::ps::Control& ctrl() const;
  inline ::ps::Control* mutable_ctrl();
  inline ::ps::Control* release_ctrl();
  inline void set_allocated_ctrl(::ps::Control* ctrl);

  // optional .ps.ParamCall param = 20;
  inline bool has_param() const;
  inline void clear_param();
  static const int kParamFieldNumber = 20;
  inline const ::ps::ParamCall& param() const;
  inline ::ps::ParamCall* mutable_param();
  inline ::ps::ParamCall* release_param();
  inline void set_allocated_param(::ps::ParamCall* param);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(Task)
  // @@protoc_insertion_point(class_scope:ps.Task)
 private:
  inline void set_has_msg();
  inline void clear_has_msg();
  inline void set_has_cmd();
  inline void clear_has_cmd();
  inline void set_has_op();
  inline void clear_has_op();
  inline void set_has_control();
  inline void clear_has_control();
  inline void set_has_request();
  inline void clear_has_request();
  inline void set_has_customer_id();
  inline void clear_has_customer_id();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_key_range();
  inline void clear_has_key_range();
  inline void set_has_key_channel();
  inline void clear_has_key_channel();
  inline void set_has_has_key();
  inline void clear_has_has_key();
  inline void set_has_key_type();
  inline void clear_has_key_type();
  inline void set_has_ctrl();
  inline void clear_has_ctrl();
  inline void set_has_param();
  inline void clear_has_param();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* msg_;
  ::google::protobuf::int32 cmd_;
  int op_;
  ::google::protobuf::int32 customer_id_;
  bool control_;
  bool request_;
  bool has_key_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > wait_time_;
  ::google::protobuf::int32 time_;
  ::google::protobuf::int32 key_channel_;
  ::ps::PbRange* key_range_;
  ::google::protobuf::RepeatedField<int> value_type_;
  mutable int _value_type_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::ps::Filter > filter_;
  ::ps::Control* ctrl_;
  ::ps::ParamCall* param_;
  int key_type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(16 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2ftask_2eproto();
  friend void protobuf_AssignDesc_proto_2ftask_2eproto();
  friend void protobuf_ShutdownFile_proto_2ftask_2eproto();

  void InitAsDefaultInstance();
  static Task* default_instance_;
};
// -------------------------------------------------------------------

class Control : public ::google::protobuf::Message {
 public:
  Control();
  virtual ~Control();

  Control(const Control& from);

  inline Control& operator=(const Control& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Control& default_instance();

  void Swap(Control* other);

  // implements Message ----------------------------------------------

  Control* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Control& from);
  void MergeFrom(const Control& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Control_Command Command;
  static const Command REGISTER_NODE = Control_Command_REGISTER_NODE;
  static const Command READY_TO_EXIT = Control_Command_READY_TO_EXIT;
  static const Command READY_TO_RUN = Control_Command_READY_TO_RUN;
  static const Command ADD_NODE = Control_Command_ADD_NODE;
  static const Command REMOVE_NODE = Control_Command_REMOVE_NODE;
  static const Command EXIT = Control_Command_EXIT;
  static inline bool Command_IsValid(int value) {
    return Control_Command_IsValid(value);
  }
  static const Command Command_MIN =
    Control_Command_Command_MIN;
  static const Command Command_MAX =
    Control_Command_Command_MAX;
  static const int Command_ARRAYSIZE =
    Control_Command_Command_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Command_descriptor() {
    return Control_Command_descriptor();
  }
  static inline const ::std::string& Command_Name(Command value) {
    return Control_Command_Name(value);
  }
  static inline bool Command_Parse(const ::std::string& name,
      Command* value) {
    return Control_Command_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .ps.Control.Command cmd = 1;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 1;
  inline ::ps::Control_Command cmd() const;
  inline void set_cmd(::ps::Control_Command value);

  // repeated .ps.Node node = 2;
  inline int node_size() const;
  inline void clear_node();
  static const int kNodeFieldNumber = 2;
  inline const ::ps::Node& node(int index) const;
  inline ::ps::Node* mutable_node(int index);
  inline ::ps::Node* add_node();
  inline const ::google::protobuf::RepeatedPtrField< ::ps::Node >&
      node() const;
  inline ::google::protobuf::RepeatedPtrField< ::ps::Node >*
      mutable_node();

  // @@protoc_insertion_point(class_scope:ps.Control)
 private:
  inline void set_has_cmd();
  inline void clear_has_cmd();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::ps::Node > node_;
  int cmd_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2ftask_2eproto();
  friend void protobuf_AssignDesc_proto_2ftask_2eproto();
  friend void protobuf_ShutdownFile_proto_2ftask_2eproto();

  void InitAsDefaultInstance();
  static Control* default_instance_;
};
// ===================================================================


// ===================================================================

// Task

// optional bytes msg = 17;
inline bool Task::has_msg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Task::set_has_msg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Task::clear_has_msg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Task::clear_msg() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    msg_->clear();
  }
  clear_has_msg();
}
inline const ::std::string& Task::msg() const {
  return *msg_;
}
inline void Task::set_msg(const ::std::string& value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void Task::set_msg(const char* value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void Task::set_msg(const void* value, size_t size) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Task::mutable_msg() {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  return msg_;
}
inline ::std::string* Task::release_msg() {
  clear_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msg_;
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Task::set_allocated_msg(::std::string* msg) {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_;
  }
  if (msg) {
    set_has_msg();
    msg_ = msg;
  } else {
    clear_has_msg();
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 cmd = 19 [default = 0];
inline bool Task::has_cmd() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Task::set_has_cmd() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Task::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Task::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 Task::cmd() const {
  return cmd_;
}
inline void Task::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
}

// optional .ps.AsOp op = 21;
inline bool Task::has_op() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Task::set_has_op() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Task::clear_has_op() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Task::clear_op() {
  op_ = 0;
  clear_has_op();
}
inline ::ps::AsOp Task::op() const {
  return static_cast< ::ps::AsOp >(op_);
}
inline void Task::set_op(::ps::AsOp value) {
  assert(::ps::AsOp_IsValid(value));
  set_has_op();
  op_ = value;
}

// optional bool control = 1 [default = false];
inline bool Task::has_control() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Task::set_has_control() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Task::clear_has_control() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Task::clear_control() {
  control_ = false;
  clear_has_control();
}
inline bool Task::control() const {
  return control_;
}
inline void Task::set_control(bool value) {
  set_has_control();
  control_ = value;
}

// optional bool request = 2 [default = false];
inline bool Task::has_request() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Task::set_has_request() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Task::clear_has_request() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Task::clear_request() {
  request_ = false;
  clear_has_request();
}
inline bool Task::request() const {
  return request_;
}
inline void Task::set_request(bool value) {
  set_has_request();
  request_ = value;
}

// optional int32 customer_id = 3;
inline bool Task::has_customer_id() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Task::set_has_customer_id() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Task::clear_has_customer_id() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Task::clear_customer_id() {
  customer_id_ = 0;
  clear_has_customer_id();
}
inline ::google::protobuf::int32 Task::customer_id() const {
  return customer_id_;
}
inline void Task::set_customer_id(::google::protobuf::int32 value) {
  set_has_customer_id();
  customer_id_ = value;
}

// optional int32 time = 5;
inline bool Task::has_time() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Task::set_has_time() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Task::clear_has_time() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Task::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 Task::time() const {
  return time_;
}
inline void Task::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
}

// repeated int32 wait_time = 6;
inline int Task::wait_time_size() const {
  return wait_time_.size();
}
inline void Task::clear_wait_time() {
  wait_time_.Clear();
}
inline ::google::protobuf::int32 Task::wait_time(int index) const {
  return wait_time_.Get(index);
}
inline void Task::set_wait_time(int index, ::google::protobuf::int32 value) {
  wait_time_.Set(index, value);
}
inline void Task::add_wait_time(::google::protobuf::int32 value) {
  wait_time_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Task::wait_time() const {
  return wait_time_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Task::mutable_wait_time() {
  return &wait_time_;
}

// optional .ps.PbRange key_range = 7;
inline bool Task::has_key_range() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Task::set_has_key_range() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Task::clear_has_key_range() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Task::clear_key_range() {
  if (key_range_ != NULL) key_range_->::ps::PbRange::Clear();
  clear_has_key_range();
}
inline const ::ps::PbRange& Task::key_range() const {
  return key_range_ != NULL ? *key_range_ : *default_instance_->key_range_;
}
inline ::ps::PbRange* Task::mutable_key_range() {
  set_has_key_range();
  if (key_range_ == NULL) key_range_ = new ::ps::PbRange;
  return key_range_;
}
inline ::ps::PbRange* Task::release_key_range() {
  clear_has_key_range();
  ::ps::PbRange* temp = key_range_;
  key_range_ = NULL;
  return temp;
}
inline void Task::set_allocated_key_range(::ps::PbRange* key_range) {
  delete key_range_;
  key_range_ = key_range;
  if (key_range) {
    set_has_key_range();
  } else {
    clear_has_key_range();
  }
}

// optional int32 key_channel = 8;
inline bool Task::has_key_channel() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Task::set_has_key_channel() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Task::clear_has_key_channel() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Task::clear_key_channel() {
  key_channel_ = 0;
  clear_has_key_channel();
}
inline ::google::protobuf::int32 Task::key_channel() const {
  return key_channel_;
}
inline void Task::set_key_channel(::google::protobuf::int32 value) {
  set_has_key_channel();
  key_channel_ = value;
}

// optional bool has_key = 9 [default = false];
inline bool Task::has_has_key() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Task::set_has_has_key() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Task::clear_has_has_key() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Task::clear_has_key() {
  has_key_ = false;
  clear_has_has_key();
}
inline bool Task::has_key() const {
  return has_key_;
}
inline void Task::set_has_key(bool value) {
  set_has_has_key();
  has_key_ = value;
}

// optional .ps.DataType key_type = 13;
inline bool Task::has_key_type() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Task::set_has_key_type() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Task::clear_has_key_type() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Task::clear_key_type() {
  key_type_ = 0;
  clear_has_key_type();
}
inline ::ps::DataType Task::key_type() const {
  return static_cast< ::ps::DataType >(key_type_);
}
inline void Task::set_key_type(::ps::DataType value) {
  assert(::ps::DataType_IsValid(value));
  set_has_key_type();
  key_type_ = value;
}

// repeated .ps.DataType value_type = 14 [packed = true];
inline int Task::value_type_size() const {
  return value_type_.size();
}
inline void Task::clear_value_type() {
  value_type_.Clear();
}
inline ::ps::DataType Task::value_type(int index) const {
  return static_cast< ::ps::DataType >(value_type_.Get(index));
}
inline void Task::set_value_type(int index, ::ps::DataType value) {
  assert(::ps::DataType_IsValid(value));
  value_type_.Set(index, value);
}
inline void Task::add_value_type(::ps::DataType value) {
  assert(::ps::DataType_IsValid(value));
  value_type_.Add(value);
}
inline const ::google::protobuf::RepeatedField<int>&
Task::value_type() const {
  return value_type_;
}
inline ::google::protobuf::RepeatedField<int>*
Task::mutable_value_type() {
  return &value_type_;
}

// repeated .ps.Filter filter = 12;
inline int Task::filter_size() const {
  return filter_.size();
}
inline void Task::clear_filter() {
  filter_.Clear();
}
inline const ::ps::Filter& Task::filter(int index) const {
  return filter_.Get(index);
}
inline ::ps::Filter* Task::mutable_filter(int index) {
  return filter_.Mutable(index);
}
inline ::ps::Filter* Task::add_filter() {
  return filter_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ps::Filter >&
Task::filter() const {
  return filter_;
}
inline ::google::protobuf::RepeatedPtrField< ::ps::Filter >*
Task::mutable_filter() {
  return &filter_;
}

// optional .ps.Control ctrl = 18;
inline bool Task::has_ctrl() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void Task::set_has_ctrl() {
  _has_bits_[0] |= 0x00004000u;
}
inline void Task::clear_has_ctrl() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void Task::clear_ctrl() {
  if (ctrl_ != NULL) ctrl_->::ps::Control::Clear();
  clear_has_ctrl();
}
inline const ::ps::Control& Task::ctrl() const {
  return ctrl_ != NULL ? *ctrl_ : *default_instance_->ctrl_;
}
inline ::ps::Control* Task::mutable_ctrl() {
  set_has_ctrl();
  if (ctrl_ == NULL) ctrl_ = new ::ps::Control;
  return ctrl_;
}
inline ::ps::Control* Task::release_ctrl() {
  clear_has_ctrl();
  ::ps::Control* temp = ctrl_;
  ctrl_ = NULL;
  return temp;
}
inline void Task::set_allocated_ctrl(::ps::Control* ctrl) {
  delete ctrl_;
  ctrl_ = ctrl;
  if (ctrl) {
    set_has_ctrl();
  } else {
    clear_has_ctrl();
  }
}

// optional .ps.ParamCall param = 20;
inline bool Task::has_param() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void Task::set_has_param() {
  _has_bits_[0] |= 0x00008000u;
}
inline void Task::clear_has_param() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void Task::clear_param() {
  if (param_ != NULL) param_->::ps::ParamCall::Clear();
  clear_has_param();
}
inline const ::ps::ParamCall& Task::param() const {
  return param_ != NULL ? *param_ : *default_instance_->param_;
}
inline ::ps::ParamCall* Task::mutable_param() {
  set_has_param();
  if (param_ == NULL) param_ = new ::ps::ParamCall;
  return param_;
}
inline ::ps::ParamCall* Task::release_param() {
  clear_has_param();
  ::ps::ParamCall* temp = param_;
  param_ = NULL;
  return temp;
}
inline void Task::set_allocated_param(::ps::ParamCall* param) {
  delete param_;
  param_ = param;
  if (param) {
    set_has_param();
  } else {
    clear_has_param();
  }
}

// -------------------------------------------------------------------

// Control

// required .ps.Control.Command cmd = 1;
inline bool Control::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Control::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Control::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Control::clear_cmd() {
  cmd_ = 2;
  clear_has_cmd();
}
inline ::ps::Control_Command Control::cmd() const {
  return static_cast< ::ps::Control_Command >(cmd_);
}
inline void Control::set_cmd(::ps::Control_Command value) {
  assert(::ps::Control_Command_IsValid(value));
  set_has_cmd();
  cmd_ = value;
}

// repeated .ps.Node node = 2;
inline int Control::node_size() const {
  return node_.size();
}
inline void Control::clear_node() {
  node_.Clear();
}
inline const ::ps::Node& Control::node(int index) const {
  return node_.Get(index);
}
inline ::ps::Node* Control::mutable_node(int index) {
  return node_.Mutable(index);
}
inline ::ps::Node* Control::add_node() {
  return node_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ps::Node >&
Control::node() const {
  return node_;
}
inline ::google::protobuf::RepeatedPtrField< ::ps::Node >*
Control::mutable_node() {
  return &node_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ps

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ps::Control_Command>() {
  return ::ps::Control_Command_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ps::DataType>() {
  return ::ps::DataType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2ftask_2eproto__INCLUDED
