// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_dump_feature.proto

#ifndef PROTOBUF_service_5fdump_5ffeature_2eproto__INCLUDED
#define PROTOBUF_service_5fdump_5ffeature_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace yidian {
namespace data {
namespace rawlog {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_service_5fdump_5ffeature_2eproto();
void protobuf_AssignDesc_service_5fdump_5ffeature_2eproto();
void protobuf_ShutdownFile_service_5fdump_5ffeature_2eproto();

class FeatureKV;
class BaseFeature;
class DocFeature;
class DumpFeature;

// ===================================================================

class FeatureKV : public ::google::protobuf::Message {
 public:
  FeatureKV();
  virtual ~FeatureKV();

  FeatureKV(const FeatureKV& from);

  inline FeatureKV& operator=(const FeatureKV& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FeatureKV& default_instance();

  void Swap(FeatureKV* other);

  // implements Message ----------------------------------------------

  inline FeatureKV* New() const { return New(NULL); }

  FeatureKV* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FeatureKV& from);
  void MergeFrom(const FeatureKV& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FeatureKV* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string k = 1;
  bool has_k() const;
  void clear_k();
  static const int kKFieldNumber = 1;
  const ::std::string& k() const;
  void set_k(const ::std::string& value);
  void set_k(const char* value);
  void set_k(const char* value, size_t size);
  ::std::string* mutable_k();
  ::std::string* release_k();
  void set_allocated_k(::std::string* k);

  // optional double v = 2;
  bool has_v() const;
  void clear_v();
  static const int kVFieldNumber = 2;
  double v() const;
  void set_v(double value);

  // @@protoc_insertion_point(class_scope:yidian.data.rawlog.FeatureKV)
 private:
  inline void set_has_k();
  inline void clear_has_k();
  inline void set_has_v();
  inline void clear_has_v();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr k_;
  double v_;
  friend void  protobuf_AddDesc_service_5fdump_5ffeature_2eproto();
  friend void protobuf_AssignDesc_service_5fdump_5ffeature_2eproto();
  friend void protobuf_ShutdownFile_service_5fdump_5ffeature_2eproto();

  void InitAsDefaultInstance();
  static FeatureKV* default_instance_;
};
// -------------------------------------------------------------------

class BaseFeature : public ::google::protobuf::Message {
 public:
  BaseFeature();
  virtual ~BaseFeature();

  BaseFeature(const BaseFeature& from);

  inline BaseFeature& operator=(const BaseFeature& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseFeature& default_instance();

  void Swap(BaseFeature* other);

  // implements Message ----------------------------------------------

  inline BaseFeature* New() const { return New(NULL); }

  BaseFeature* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseFeature& from);
  void MergeFrom(const BaseFeature& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BaseFeature* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // repeated .yidian.data.rawlog.FeatureKV values = 2;
  int values_size() const;
  void clear_values();
  static const int kValuesFieldNumber = 2;
  const ::yidian::data::rawlog::FeatureKV& values(int index) const;
  ::yidian::data::rawlog::FeatureKV* mutable_values(int index);
  ::yidian::data::rawlog::FeatureKV* add_values();
  const ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::FeatureKV >&
      values() const;
  ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::FeatureKV >*
      mutable_values();

  // @@protoc_insertion_point(class_scope:yidian.data.rawlog.BaseFeature)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::FeatureKV > values_;
  friend void  protobuf_AddDesc_service_5fdump_5ffeature_2eproto();
  friend void protobuf_AssignDesc_service_5fdump_5ffeature_2eproto();
  friend void protobuf_ShutdownFile_service_5fdump_5ffeature_2eproto();

  void InitAsDefaultInstance();
  static BaseFeature* default_instance_;
};
// -------------------------------------------------------------------

class DocFeature : public ::google::protobuf::Message {
 public:
  DocFeature();
  virtual ~DocFeature();

  DocFeature(const DocFeature& from);

  inline DocFeature& operator=(const DocFeature& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DocFeature& default_instance();

  void Swap(DocFeature* other);

  // implements Message ----------------------------------------------

  inline DocFeature* New() const { return New(NULL); }

  DocFeature* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DocFeature& from);
  void MergeFrom(const DocFeature& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DocFeature* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string doc_id = 1;
  bool has_doc_id() const;
  void clear_doc_id();
  static const int kDocIdFieldNumber = 1;
  const ::std::string& doc_id() const;
  void set_doc_id(const ::std::string& value);
  void set_doc_id(const char* value);
  void set_doc_id(const char* value, size_t size);
  ::std::string* mutable_doc_id();
  ::std::string* release_doc_id();
  void set_allocated_doc_id(::std::string* doc_id);

  // repeated int32 ids = 3;
  int ids_size() const;
  void clear_ids();
  static const int kIdsFieldNumber = 3;
  ::google::protobuf::int32 ids(int index) const;
  void set_ids(int index, ::google::protobuf::int32 value);
  void add_ids(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_ids();

  // optional double score = 4;
  bool has_score() const;
  void clear_score();
  static const int kScoreFieldNumber = 4;
  double score() const;
  void set_score(double value);

  // optional int32 times = 5;
  bool has_times() const;
  void clear_times();
  static const int kTimesFieldNumber = 5;
  ::google::protobuf::int32 times() const;
  void set_times(::google::protobuf::int32 value);

  // optional double gbdtscore = 6;
  bool has_gbdtscore() const;
  void clear_gbdtscore();
  static const int kGbdtscoreFieldNumber = 6;
  double gbdtscore() const;
  void set_gbdtscore(double value);

  // optional double y = 7;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 7;
  double y() const;
  void set_y(double value);

  // repeated .yidian.data.rawlog.BaseFeature features = 8;
  int features_size() const;
  void clear_features();
  static const int kFeaturesFieldNumber = 8;
  const ::yidian::data::rawlog::BaseFeature& features(int index) const;
  ::yidian::data::rawlog::BaseFeature* mutable_features(int index);
  ::yidian::data::rawlog::BaseFeature* add_features();
  const ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::BaseFeature >&
      features() const;
  ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::BaseFeature >*
      mutable_features();

  // @@protoc_insertion_point(class_scope:yidian.data.rawlog.DocFeature)
 private:
  inline void set_has_doc_id();
  inline void clear_has_doc_id();
  inline void set_has_score();
  inline void clear_has_score();
  inline void set_has_times();
  inline void clear_has_times();
  inline void set_has_gbdtscore();
  inline void clear_has_gbdtscore();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr doc_id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > ids_;
  double score_;
  double gbdtscore_;
  double y_;
  ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::BaseFeature > features_;
  ::google::protobuf::int32 times_;
  friend void  protobuf_AddDesc_service_5fdump_5ffeature_2eproto();
  friend void protobuf_AssignDesc_service_5fdump_5ffeature_2eproto();
  friend void protobuf_ShutdownFile_service_5fdump_5ffeature_2eproto();

  void InitAsDefaultInstance();
  static DocFeature* default_instance_;
};
// -------------------------------------------------------------------

class DumpFeature : public ::google::protobuf::Message {
 public:
  DumpFeature();
  virtual ~DumpFeature();

  DumpFeature(const DumpFeature& from);

  inline DumpFeature& operator=(const DumpFeature& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DumpFeature& default_instance();

  void Swap(DumpFeature* other);

  // implements Message ----------------------------------------------

  inline DumpFeature* New() const { return New(NULL); }

  DumpFeature* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DumpFeature& from);
  void MergeFrom(const DumpFeature& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DumpFeature* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // optional string user_id = 1;
  bool has_user_id() const;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  const ::std::string& user_id() const;
  void set_user_id(const ::std::string& value);
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  ::std::string* mutable_user_id();
  ::std::string* release_user_id();
  void set_allocated_user_id(::std::string* user_id);

  // repeated .yidian.data.rawlog.DocFeature docs = 2;
  int docs_size() const;
  void clear_docs();
  static const int kDocsFieldNumber = 2;
  const ::yidian::data::rawlog::DocFeature& docs(int index) const;
  ::yidian::data::rawlog::DocFeature* mutable_docs(int index);
  ::yidian::data::rawlog::DocFeature* add_docs();
  const ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::DocFeature >&
      docs() const;
  ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::DocFeature >*
      mutable_docs();

  // optional int64 timestamp = 3;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // optional string version = 4;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 4;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // optional string buckets = 5;
  bool has_buckets() const;
  void clear_buckets();
  static const int kBucketsFieldNumber = 5;
  const ::std::string& buckets() const;
  void set_buckets(const ::std::string& value);
  void set_buckets(const char* value);
  void set_buckets(const char* value, size_t size);
  ::std::string* mutable_buckets();
  ::std::string* release_buckets();
  void set_allocated_buckets(::std::string* buckets);

  // map<string, string> contexts = 6;
  int contexts_size() const;
  void clear_contexts();
  static const int kContextsFieldNumber = 6;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      contexts() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_contexts();

  // @@protoc_insertion_point(class_scope:yidian.data.rawlog.DumpFeature)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_buckets();
  inline void clear_has_buckets();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr user_id_;
  ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::DocFeature > docs_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::internal::ArenaStringPtr buckets_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 >
      DumpFeature_ContextsEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > contexts_;
  friend void  protobuf_AddDesc_service_5fdump_5ffeature_2eproto();
  friend void protobuf_AssignDesc_service_5fdump_5ffeature_2eproto();
  friend void protobuf_ShutdownFile_service_5fdump_5ffeature_2eproto();

  void InitAsDefaultInstance();
  static DumpFeature* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// FeatureKV

// optional string k = 1;
inline bool FeatureKV::has_k() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FeatureKV::set_has_k() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FeatureKV::clear_has_k() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FeatureKV::clear_k() {
  k_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_k();
}
inline const ::std::string& FeatureKV::k() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.FeatureKV.k)
  return k_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FeatureKV::set_k(const ::std::string& value) {
  set_has_k();
  k_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.FeatureKV.k)
}
inline void FeatureKV::set_k(const char* value) {
  set_has_k();
  k_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yidian.data.rawlog.FeatureKV.k)
}
inline void FeatureKV::set_k(const char* value, size_t size) {
  set_has_k();
  k_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yidian.data.rawlog.FeatureKV.k)
}
inline ::std::string* FeatureKV::mutable_k() {
  set_has_k();
  // @@protoc_insertion_point(field_mutable:yidian.data.rawlog.FeatureKV.k)
  return k_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FeatureKV::release_k() {
  clear_has_k();
  return k_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FeatureKV::set_allocated_k(::std::string* k) {
  if (k != NULL) {
    set_has_k();
  } else {
    clear_has_k();
  }
  k_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), k);
  // @@protoc_insertion_point(field_set_allocated:yidian.data.rawlog.FeatureKV.k)
}

// optional double v = 2;
inline bool FeatureKV::has_v() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FeatureKV::set_has_v() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FeatureKV::clear_has_v() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FeatureKV::clear_v() {
  v_ = 0;
  clear_has_v();
}
inline double FeatureKV::v() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.FeatureKV.v)
  return v_;
}
inline void FeatureKV::set_v(double value) {
  set_has_v();
  v_ = value;
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.FeatureKV.v)
}

// -------------------------------------------------------------------

// BaseFeature

// optional string name = 1;
inline bool BaseFeature::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BaseFeature::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BaseFeature::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BaseFeature::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& BaseFeature::name() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.BaseFeature.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseFeature::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.BaseFeature.name)
}
inline void BaseFeature::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yidian.data.rawlog.BaseFeature.name)
}
inline void BaseFeature::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yidian.data.rawlog.BaseFeature.name)
}
inline ::std::string* BaseFeature::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:yidian.data.rawlog.BaseFeature.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BaseFeature::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseFeature::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:yidian.data.rawlog.BaseFeature.name)
}

// repeated .yidian.data.rawlog.FeatureKV values = 2;
inline int BaseFeature::values_size() const {
  return values_.size();
}
inline void BaseFeature::clear_values() {
  values_.Clear();
}
inline const ::yidian::data::rawlog::FeatureKV& BaseFeature::values(int index) const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.BaseFeature.values)
  return values_.Get(index);
}
inline ::yidian::data::rawlog::FeatureKV* BaseFeature::mutable_values(int index) {
  // @@protoc_insertion_point(field_mutable:yidian.data.rawlog.BaseFeature.values)
  return values_.Mutable(index);
}
inline ::yidian::data::rawlog::FeatureKV* BaseFeature::add_values() {
  // @@protoc_insertion_point(field_add:yidian.data.rawlog.BaseFeature.values)
  return values_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::FeatureKV >&
BaseFeature::values() const {
  // @@protoc_insertion_point(field_list:yidian.data.rawlog.BaseFeature.values)
  return values_;
}
inline ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::FeatureKV >*
BaseFeature::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:yidian.data.rawlog.BaseFeature.values)
  return &values_;
}

// -------------------------------------------------------------------

// DocFeature

// optional string doc_id = 1;
inline bool DocFeature::has_doc_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DocFeature::set_has_doc_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DocFeature::clear_has_doc_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DocFeature::clear_doc_id() {
  doc_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_doc_id();
}
inline const ::std::string& DocFeature::doc_id() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DocFeature.doc_id)
  return doc_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DocFeature::set_doc_id(const ::std::string& value) {
  set_has_doc_id();
  doc_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DocFeature.doc_id)
}
inline void DocFeature::set_doc_id(const char* value) {
  set_has_doc_id();
  doc_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yidian.data.rawlog.DocFeature.doc_id)
}
inline void DocFeature::set_doc_id(const char* value, size_t size) {
  set_has_doc_id();
  doc_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yidian.data.rawlog.DocFeature.doc_id)
}
inline ::std::string* DocFeature::mutable_doc_id() {
  set_has_doc_id();
  // @@protoc_insertion_point(field_mutable:yidian.data.rawlog.DocFeature.doc_id)
  return doc_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DocFeature::release_doc_id() {
  clear_has_doc_id();
  return doc_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DocFeature::set_allocated_doc_id(::std::string* doc_id) {
  if (doc_id != NULL) {
    set_has_doc_id();
  } else {
    clear_has_doc_id();
  }
  doc_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), doc_id);
  // @@protoc_insertion_point(field_set_allocated:yidian.data.rawlog.DocFeature.doc_id)
}

// repeated int32 ids = 3;
inline int DocFeature::ids_size() const {
  return ids_.size();
}
inline void DocFeature::clear_ids() {
  ids_.Clear();
}
inline ::google::protobuf::int32 DocFeature::ids(int index) const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DocFeature.ids)
  return ids_.Get(index);
}
inline void DocFeature::set_ids(int index, ::google::protobuf::int32 value) {
  ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DocFeature.ids)
}
inline void DocFeature::add_ids(::google::protobuf::int32 value) {
  ids_.Add(value);
  // @@protoc_insertion_point(field_add:yidian.data.rawlog.DocFeature.ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DocFeature::ids() const {
  // @@protoc_insertion_point(field_list:yidian.data.rawlog.DocFeature.ids)
  return ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DocFeature::mutable_ids() {
  // @@protoc_insertion_point(field_mutable_list:yidian.data.rawlog.DocFeature.ids)
  return &ids_;
}

// optional double score = 4;
inline bool DocFeature::has_score() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DocFeature::set_has_score() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DocFeature::clear_has_score() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DocFeature::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline double DocFeature::score() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DocFeature.score)
  return score_;
}
inline void DocFeature::set_score(double value) {
  set_has_score();
  score_ = value;
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DocFeature.score)
}

// optional int32 times = 5;
inline bool DocFeature::has_times() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DocFeature::set_has_times() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DocFeature::clear_has_times() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DocFeature::clear_times() {
  times_ = 0;
  clear_has_times();
}
inline ::google::protobuf::int32 DocFeature::times() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DocFeature.times)
  return times_;
}
inline void DocFeature::set_times(::google::protobuf::int32 value) {
  set_has_times();
  times_ = value;
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DocFeature.times)
}

// optional double gbdtscore = 6;
inline bool DocFeature::has_gbdtscore() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DocFeature::set_has_gbdtscore() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DocFeature::clear_has_gbdtscore() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DocFeature::clear_gbdtscore() {
  gbdtscore_ = 0;
  clear_has_gbdtscore();
}
inline double DocFeature::gbdtscore() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DocFeature.gbdtscore)
  return gbdtscore_;
}
inline void DocFeature::set_gbdtscore(double value) {
  set_has_gbdtscore();
  gbdtscore_ = value;
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DocFeature.gbdtscore)
}

// optional double y = 7;
inline bool DocFeature::has_y() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void DocFeature::set_has_y() {
  _has_bits_[0] |= 0x00000020u;
}
inline void DocFeature::clear_has_y() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void DocFeature::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double DocFeature::y() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DocFeature.y)
  return y_;
}
inline void DocFeature::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DocFeature.y)
}

// repeated .yidian.data.rawlog.BaseFeature features = 8;
inline int DocFeature::features_size() const {
  return features_.size();
}
inline void DocFeature::clear_features() {
  features_.Clear();
}
inline const ::yidian::data::rawlog::BaseFeature& DocFeature::features(int index) const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DocFeature.features)
  return features_.Get(index);
}
inline ::yidian::data::rawlog::BaseFeature* DocFeature::mutable_features(int index) {
  // @@protoc_insertion_point(field_mutable:yidian.data.rawlog.DocFeature.features)
  return features_.Mutable(index);
}
inline ::yidian::data::rawlog::BaseFeature* DocFeature::add_features() {
  // @@protoc_insertion_point(field_add:yidian.data.rawlog.DocFeature.features)
  return features_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::BaseFeature >&
DocFeature::features() const {
  // @@protoc_insertion_point(field_list:yidian.data.rawlog.DocFeature.features)
  return features_;
}
inline ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::BaseFeature >*
DocFeature::mutable_features() {
  // @@protoc_insertion_point(field_mutable_list:yidian.data.rawlog.DocFeature.features)
  return &features_;
}

// -------------------------------------------------------------------

// DumpFeature

// optional string user_id = 1;
inline bool DumpFeature::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DumpFeature::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DumpFeature::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DumpFeature::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_id();
}
inline const ::std::string& DumpFeature::user_id() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DumpFeature.user_id)
  return user_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DumpFeature::set_user_id(const ::std::string& value) {
  set_has_user_id();
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DumpFeature.user_id)
}
inline void DumpFeature::set_user_id(const char* value) {
  set_has_user_id();
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yidian.data.rawlog.DumpFeature.user_id)
}
inline void DumpFeature::set_user_id(const char* value, size_t size) {
  set_has_user_id();
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yidian.data.rawlog.DumpFeature.user_id)
}
inline ::std::string* DumpFeature::mutable_user_id() {
  set_has_user_id();
  // @@protoc_insertion_point(field_mutable:yidian.data.rawlog.DumpFeature.user_id)
  return user_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DumpFeature::release_user_id() {
  clear_has_user_id();
  return user_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DumpFeature::set_allocated_user_id(::std::string* user_id) {
  if (user_id != NULL) {
    set_has_user_id();
  } else {
    clear_has_user_id();
  }
  user_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:yidian.data.rawlog.DumpFeature.user_id)
}

// repeated .yidian.data.rawlog.DocFeature docs = 2;
inline int DumpFeature::docs_size() const {
  return docs_.size();
}
inline void DumpFeature::clear_docs() {
  docs_.Clear();
}
inline const ::yidian::data::rawlog::DocFeature& DumpFeature::docs(int index) const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DumpFeature.docs)
  return docs_.Get(index);
}
inline ::yidian::data::rawlog::DocFeature* DumpFeature::mutable_docs(int index) {
  // @@protoc_insertion_point(field_mutable:yidian.data.rawlog.DumpFeature.docs)
  return docs_.Mutable(index);
}
inline ::yidian::data::rawlog::DocFeature* DumpFeature::add_docs() {
  // @@protoc_insertion_point(field_add:yidian.data.rawlog.DumpFeature.docs)
  return docs_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::DocFeature >&
DumpFeature::docs() const {
  // @@protoc_insertion_point(field_list:yidian.data.rawlog.DumpFeature.docs)
  return docs_;
}
inline ::google::protobuf::RepeatedPtrField< ::yidian::data::rawlog::DocFeature >*
DumpFeature::mutable_docs() {
  // @@protoc_insertion_point(field_mutable_list:yidian.data.rawlog.DumpFeature.docs)
  return &docs_;
}

// optional int64 timestamp = 3;
inline bool DumpFeature::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DumpFeature::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DumpFeature::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DumpFeature::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 DumpFeature::timestamp() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DumpFeature.timestamp)
  return timestamp_;
}
inline void DumpFeature::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DumpFeature.timestamp)
}

// optional string version = 4;
inline bool DumpFeature::has_version() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DumpFeature::set_has_version() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DumpFeature::clear_has_version() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DumpFeature::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_version();
}
inline const ::std::string& DumpFeature::version() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DumpFeature.version)
  return version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DumpFeature::set_version(const ::std::string& value) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DumpFeature.version)
}
inline void DumpFeature::set_version(const char* value) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yidian.data.rawlog.DumpFeature.version)
}
inline void DumpFeature::set_version(const char* value, size_t size) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yidian.data.rawlog.DumpFeature.version)
}
inline ::std::string* DumpFeature::mutable_version() {
  set_has_version();
  // @@protoc_insertion_point(field_mutable:yidian.data.rawlog.DumpFeature.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DumpFeature::release_version() {
  clear_has_version();
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DumpFeature::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    set_has_version();
  } else {
    clear_has_version();
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:yidian.data.rawlog.DumpFeature.version)
}

// optional string buckets = 5;
inline bool DumpFeature::has_buckets() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DumpFeature::set_has_buckets() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DumpFeature::clear_has_buckets() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DumpFeature::clear_buckets() {
  buckets_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_buckets();
}
inline const ::std::string& DumpFeature::buckets() const {
  // @@protoc_insertion_point(field_get:yidian.data.rawlog.DumpFeature.buckets)
  return buckets_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DumpFeature::set_buckets(const ::std::string& value) {
  set_has_buckets();
  buckets_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yidian.data.rawlog.DumpFeature.buckets)
}
inline void DumpFeature::set_buckets(const char* value) {
  set_has_buckets();
  buckets_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yidian.data.rawlog.DumpFeature.buckets)
}
inline void DumpFeature::set_buckets(const char* value, size_t size) {
  set_has_buckets();
  buckets_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yidian.data.rawlog.DumpFeature.buckets)
}
inline ::std::string* DumpFeature::mutable_buckets() {
  set_has_buckets();
  // @@protoc_insertion_point(field_mutable:yidian.data.rawlog.DumpFeature.buckets)
  return buckets_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DumpFeature::release_buckets() {
  clear_has_buckets();
  return buckets_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DumpFeature::set_allocated_buckets(::std::string* buckets) {
  if (buckets != NULL) {
    set_has_buckets();
  } else {
    clear_has_buckets();
  }
  buckets_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buckets);
  // @@protoc_insertion_point(field_set_allocated:yidian.data.rawlog.DumpFeature.buckets)
}

// map<string, string> contexts = 6;
inline int DumpFeature::contexts_size() const {
  return contexts_.size();
}
inline void DumpFeature::clear_contexts() {
  contexts_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
DumpFeature::contexts() const {
  // @@protoc_insertion_point(field_map:yidian.data.rawlog.DumpFeature.contexts)
  return contexts_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
DumpFeature::mutable_contexts() {
  // @@protoc_insertion_point(field_mutable_map:yidian.data.rawlog.DumpFeature.contexts)
  return contexts_.MutableMap();
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rawlog
}  // namespace data
}  // namespace yidian

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_service_5fdump_5ffeature_2eproto__INCLUDED
